# -*- coding: utf-8 -*-
"""cn_add.py -- 新增界面文本词表（选项名 / 选项值）。键必须与模组原文逐字符一致。"""

CN_ADD = {
    # ---------- 通用值 ----------
    'All': '全部',
    'Default': '默认',
    'Off': '关',
    'On': '开',
    'On (default)': '开（默认）',
    'OFF': '关',
    'Show': '显示',
    'Hide': '隐藏',
    'Dim': '暗淡',
    'Red': '红色',
    'Green': '绿色',
    'Standard': '标准',
    'Mild': '轻微',
    'Stable': '稳定',
    'Planted': '沉稳',
    'Balanced': '均衡',
    'Combined': '组合',
    'Integrated': '一体化',
    'Rings': '圆环',
    'Simple': '简洁',
    'Faint': '微弱',
    'Full brightness': '全亮',
    'Line': '线状',
    'Glow': '光晕',
    'Gameplay': '游戏性',
    'Task Light': '作业灯',
    'Core': '核心',
    'Cells': '显示项目',
    'Squad': '小队',
    'Stratagems': '战略配备',
    'Textures': '贴图',
    'textures': '贴图',

    # ---------- 通用描述短语 ----------
    'Default.': '默认。',
    'Default. Stays visible, faded.': '默认。保持可见但变暗。',
    'Always fully visible.': '始终完全可见。',
    'Pick one colour.': '选择一种颜色。',
    'Both.': '两者都启用。',
    'made by Dekr0': '作者：Dekr0',
    'This is the default mod, no added music.': '默认版本，无附加音乐。',

    # ---------- 数字/角度（保持信息完整） ----------
    '1.9 m up.': '高度 1.9 米。',
    '2.2 m up.': '高度 2.2 米。',
    '2.5 m up: the widest view.': '高度 2.5 米：视野最广。',
    '6 degrees below to 30 above.': '下 6 度至上方 30 度。',
    '10 degrees below to 35 above.': '下 10 度至上方 35 度。',
    '15 degrees below to 45 above.': '下 15 度至上方 45 度。',
    'About 31 degrees a second.': '约每秒 31 度。',
    'About 44 degrees a second.': '约每秒 44 度。',
    '37.5 degrees a second.': '每秒 37.5 度。',
    '50 degrees a second.': '每秒 50 度。',
    '52.5 degrees a second.': '每秒 52.5 度。',
    '70 degrees a second.': '每秒 70 度。',
    'A quarter more grip.': '抓地力 +25%。',
    'A quarter more pulling power.': '牵引力 +25%。',
    'A quarter quicker.': '转向快 25%。',
    'Half again as quick.': '转向快 50%。',
    'Half again the grip.': '抓地力 +50%。',
    'Half again the pulling power.': '牵引力 +50%。',
    'Twice the pulling power.': '牵引力 ×2。',

    # ---------- Castle ODST ----------
    'Castle': 'Castle',
    'UA Camo': '内衬迷彩',
    'Under Armor Camo': '内衬迷彩',
    'Armor Camo': '护甲迷彩',
    'Camo on Armor': '护甲迷彩',
    'Black ODST': '黑色 ODST',
    'Black/greys with no camo': '黑灰色，无迷彩',
    'Replaces CPG-48 Snapper': '替换 CPG-48「工兵」',

    # ---------- ODST Loner ----------
    'DP8': 'DP8',
    'RS67': 'RS67',
    'A9': 'A9',
    'Replaces medium siege ready set': '替换中型攻坚套装',
    'Replaces medium stealth set': '替换中型潜行套装',
    'Replaces helljumper set': '替换「地狱伞兵」套装',
    'Required for all replacers': '所有替换外观共用，必需',

    # ---------- Glowing Supply Icons ----------
    'Ammo Box': '弹药箱',
    'Stim Box': '兴奋剂箱',
    'Grenade Box': '手雷箱',
    'Supply Pod': '补给舱',
    'Support Weapon Pod': '支援武器舱',
    'Icon and Glow': '图标 + 光晕',
    'Icon and Glow LARGER': '图标 + 光晕（更大）',
    'Icon and Glow LODs': '图标 + 光晕（含远距 LOD）',
    'Glow Only': '仅光晕',
    'No Glow': '无光晕',
    'Static Icon': '静态图标',
    'Larger Icon Appears When Far': '远距离时显示更大图标',
    "Doesn't Support LODs Large Icon Only": '不支持远距 LOD，仅显示大图标',

    # ---------- Super Laser Sights ----------
    'Sentry Turrets': '哨戒炮塔',
    'Guard Dog Drones': '护卫犬无人机',
    'Red': '红色',
    'Green': '绿色',

    # ---------- Smarter Guard Dogs & Sentries ----------
    'Smarter Guard Dogs and Sentries': '更聪明的护卫犬与哨戒炮',
    'Guard Dogs': '护卫犬',
    'Sentries': '哨戒炮',
    'All sentries': '所有哨戒炮',
    'All but the Tesla Tower': '除特斯拉塔外的所有哨戒炮',
    'Every sentry, the Tesla Tower included.': '所有哨戒炮，包括特斯拉塔。',
    'Intelligence': '智能判断',
    'Armor Intelligence and Target Prioritization': '装甲判断 + 目标优先级',
    'Only Armor Intelligence': '仅装甲判断',
    'Only Target Prioritization': '仅目标优先级',
    'Safety': '安全保护',
    'You and your teammates': '你与队友',
    'Only you': '仅你',
    'Only your teammates': '仅队友',
    'Protects you and the other players.': '保护你和其他玩家。',
    'Targeting Laser': '瞄准激光',
    'Laser Brightness': '激光亮度',
    'Normal (100%)': '正常（100%）',
    'Dim (50%)': '暗淡（50%）',
    'Softer (75%)': '柔化（75%）',
    'Bright (150%)': '明亮（150%）',
    'Brightest (200%)': '最亮（200%）',
    'The laser as it has always been.': '与原版一致的激光。',

    # ---------- Aggro Counter ----------
    'Aggro Counter': '仇恨计数',
    'Position': '位置',
    'Size': '尺寸',
    'Left of the compass': '罗盘左侧',
    'Right of the compass': '罗盘右侧',
    'Under the warning banners': '警告横幅下方',
    'Nearby only': '仅附近',
    'Without nearby': '不含附近',
    'Searching + On you': '搜索中 + 锁定你',
    'Searching, on you and on teammates.': '搜索中、锁定你、锁定队友。',
    'Only the enemies that are after you.': '只统计正在追击你的敌人。',
    'When nothing is counted': '计数全为零时',
    'The counter badge. Required.': '计数器徽章。必需。',

    # ---------- Helmet Headlamp ----------
    'Default mode': '默认模式',
    'The headlamp controller. Required.': '头灯控制器。必需。',
    'Gameplay-first flood, about 35-40 m.': '偏游戏性的泛光照明，约 35-40 米。',

    # ---------- HD2 Transmog Foundation ----------
    'HD2 Transmog Foundation': 'HD2 Transmog Foundation',
    'Independent armor stats (default)': '独立护甲属性（默认）',
    'Disable armor stat selection': '禁用护甲属性选择',
    'Choose look, base stats, then passive.': '依次选择外观、基础属性、被动。',
    'Helmet and cape variants': '头盔与披风变体',
    'Disable helmet and cape variants.': '禁用头盔与披风变体。',
    'Armor thumbnail passive icons': '护甲缩略图被动图标',
    'Show passive badges on armor thumbnails.': '在护甲缩略图上显示被动徽章。',

    # ---------- Armored Overhaul ----------
    'Tank Power': '坦克动力',
    'Tank Grip': '坦克抓地',
    'Tank Steering': '坦克转向',
    'Tank Suspension': '坦克悬挂',
    'Strong (x1.25)': '强（×1.25）',
    'Stronger (x1.5)': '更强（×1.5）',
    'Strongest (x2)': '最强（×2）',
    'Moderate (x1.25)': '中等（×1.25）',
    'Strong (x1.5)': '强（×1.5）',
    'Maximum (x2)': '最大（×2）',
    'Responsive (x1.25)': '灵敏（×1.25）',
    'Quick (x1.5)': '快速（×1.5）',
    'Sharp (x2)': '锐利（×2）',
    'Quick (x1.25)': '快速（×1.25）',
    'Fast (x1.5)': '迅捷（×1.5）',
    'Very fast (x2)': '极快（×2）',
    'Wide (-6..+30 deg)': '宽（-6..+30 度）',
    'Wider (-10..+35 deg)': '更宽（-10..+35 度）',
    'Widest (-15..+45 deg)': '最宽（-15..+45 度）',
    'Tank MBT Turrets': '坦克炮塔全向旋转',
    'Tank Turret Traverse': '炮塔回旋速度',
    'Tank Turret Elevation': '炮塔俯仰速度',
    'Tank Turret Aim Range': '炮塔俯仰范围',
    'Tank Autoloader': '坦克自动装填',
    'Gunner Drive': '炮手位驾驶',
    'Tanks and FRV': '坦克与 FRV',
    'Tanks': '坦克',
    'Tank Gunner Camera': '坦克炮手视角',
    'Close (1 m behind)': '近（后方 1 米）',
    'Far (3.5 m behind)': '远（后方 3.5 米）',
    'Farther (5.4 m behind)': '更远（后方 5.4 米）',
    'Farthest (7.4 m behind)': '最远（后方 7.4 米）',
    'Both the tanks and the M-102 FRV.': '坦克和 M-102 FRV 都启用。',
    'The M-102 FRV, from its gunner seat.': 'M-102 FRV，可在炮手座驾驶。',
    'FRV Stability': 'FRV 稳定性',
    'Vehicle Indicator': '载具指示器',

    # ---------- Better Map Markers ----------
    'Minimap Settings (Map Marker)': '小地图设置（地图标记）',
    'Minimap Settings (Enemy Blips)': '小地图设置（敌人光点）',
    'Minimap Settings (View Cones)': '小地图设置（视野扇形）',
    'Compass Settings (Super Destroyer Indicator)': '罗盘设置（超级驱逐舰指示）',
    'DIAMOND (GAPPED, OUTLINED)': '菱形（间断、描边）',
    'DIAMOND (GAPPED)': '菱形（间断）',
    'DIAMOND (THICK, GAPPED, OUTLINED)': '菱形（粗、间断、描边）',
    'DIAMOND (THICK, GAPPED)': '菱形（粗、间断）',
    'DIAMOND (THICK, OUTLINED)': '菱形（粗、描边）',
    'DIAMOND (THICK)': '菱形（粗）',
    'DIAMOND (THICK, HOLLOWED, OUTLINED)': '菱形（粗、空心、描边）',
    'DIAMOND (THICK, HOLLOWED)': '菱形（粗、空心）',
    'DIAMOND (THICK, HOLLOWED, GAPPED, OUTLINED)': '菱形（粗、空心、间断、描边）',
    'DIAMOND (THICK, HOLLOWED, GAPPED)': '菱形（粗、空心、间断）',
    'HEXAGON (OUTLINED)': '六边形（描边）',
    'HEXAGON': '六边形',
    'RING (OUTLINED)': '圆环（描边）',
    'RING': '圆环',
    'POINTERS (OUTLINED)': '指针（描边）',
    'POINTERS': '指针',
    'ARROWS (OUTLINED)': '箭头（描边）',
    'ARROWS': '箭头',
    'CROSS (OUTLINED)': '十字（描边）',
    'CROSS': '十字',
    'CIRCLE (SMALL)': '圆形（小）',
    'SKULL (SMALL)': '骷髅（小）',
    'SKULL': '骷髅',
    'SUPER DESTROYER': '超级驱逐舰',
    'OUTLINED': '描边',
    'VANILLA': '原版',

    # ---------- HD2 HUD+ ----------
    'HUD layout': 'HUD 布局',
    'Show when idle': '待机时显示',
    'Game crosshair': '游戏自带准星',
    'HD2 HUD+': 'HD2 HUD+',

    # ---------- Concept Mech ----------
    'All Mechs': '全部机甲',

    # ---------- Muzzle Flash Smoke Remover ----------
    'No Muzzle Flash Smoke': '枪口无烟',
    'No Smoke Heat or Sparks - LAS 16 Sickle': '无烟、无热浪、无火花 - LAS-16 镰刀',
    'No Smoke Heat or Sparks - LAS 17 DE Sickle - Talon': '无烟、无热浪、无火花 - LAS-17 DE 镰刀 - 爪',

    # ---------- Enhanced Sentries Revamped ----------
    'Autocannon Sentry': '机炮哨戒炮',
    'Gatling Sentry': '加特林哨戒炮',
    'Machinegun Sentry': '机枪哨戒炮',
    'Mortar Sentry': '迫击炮哨戒炮',
    'Rocket Sentry': '火箭哨戒炮',
    'Flak36': 'Flak36',
    'Flak36 (no pings)': 'Flak36（无提示音）',
    'Flak36 (quieter pings)': 'Flak36（提示音更轻）',
    'Flakm42': 'Flakm42',
    'Flakm42 (no pings)': 'Flakm42（无提示音）',
    'Flakm42 (quieter pings)': 'Flakm42（提示音更轻）',
    'KWK36': 'KWK36',
    'KWK36 (no pings)': 'KWK36（无提示音）',
    'KWK36 (quieter pings)': 'KWK36（提示音更轻）',
    '40mm bofors': '40mm 博福斯',
    'QF 2 Pounder': 'QF 2 磅炮',
    'Gau-19': 'Gau-19',
    'Gau-12': 'Gau-12',
    'M197': 'M197',
    'M61': 'M61',
    'C-RAM': 'C-RAM',
    'M134': 'M134',
    'BAR': 'BAR',
    'MG34': 'MG34',
    'MG42': 'MG42',
    'M240': 'M240',
    'MG3': 'MG3',
    'PKM': 'PKM',
    'BF1 Mortar': 'BF1 迫击炮',
    'Squad 81mm': '小队 81mm 迫击炮',
    'Malyutka': 'Malyutka',
    'Hydra': 'Hydra',

    # ---------- Menacing Heavy Weapons ----------
    'Menacing Recoilless Rifle': '威压 无后坐力步枪',
    'Menacing Laser Cannon': '威压 激光炮',
    'Menacing Quasar Cannon': '威压 类星体炮',
    'Menacing Autocannon': '威压 机炮',
    'Menacing Railgun': '威压 磁轨炮',
    'Menacing Epoch': '威压 Epoch',
    'Menacing Flamethrower': '威压 火焰喷射器',
    'Menacing Spear': '威压 长矛',
    'Menacing Exosuits': '威压 外骨骼',
    'Menacing HMG': '威压 重机枪',
    'Menacing Maxigun': '威压 转轮机枪',
    'Quiet Ping': '轻提示音',
    'Loud Ping': '明显提示音',
    'UnSafe Mode': '不安全模式',
    'Safe Mode': '安全模式',
    'Standard Horn': '标准号角',
    'MVM Horn': 'MvM 号角',
    '40K Horn': '40K 号角',
    'Meet The Medic': 'Meet The Medic',
    'Changes firing, idle, and repel sounds.': '替换开火、待机与驱离音效。',
}
