# -*- coding: utf-8 -*-
"""cn_strings.py —— 英文原文 -> 简体中文 词表（Mod Options Menu 选项文本 / 模组名 / 选项说明）。

合并自 cn_add / cn_desc / cn_fix / cn_mods / cn_mods2 / cn_new，共 541 条；
键必须与模组注册时传入的字符串逐字符一致。
"""

CN = {
    'All': '全部',
    'Default': '默认',
    'Off': '关',
    'On': '开',
    'On (default)': '开（默认）',
    'OFF': '关',
    'Show': '显示',
    'Hide': '隐藏',
    'Dim': '暗淡',
    'Red': '红色',
    'Green': '绿色',
    'Standard': '标准',
    'Mild': '轻微',
    'Stable': '稳定',
    'Planted': '沉稳',
    'Balanced': '均衡',
    'Combined': '组合',
    'Integrated': '一体化',
    'Rings': '圆环',
    'Simple': '简洁',
    'Faint': '微弱',
    'Full brightness': '全亮',
    'Line': '线状',
    'Glow': '光晕',
    'Gameplay': '游戏性',
    'Task Light': '作业灯',
    'Core': '核心',
    'Cells': '显示项目',
    'Squad': '小队',
    'Stratagems': '战略配备',
    'Textures': '贴图',
    'textures': '贴图',
    'Default.': '默认。',
    'Default. Stays visible, faded.': '默认。保持可见但变暗。',
    'Always fully visible.': '始终完全可见。',
    'Pick one colour.': '选择一种颜色。',
    'Both.': '两者都启用。',
    'made by Dekr0': '作者：Dekr0',
    'This is the default mod, no added music.': '默认版本，无附加音乐。',
    '1.9 m up.': '高度 1.9 米。',
    '2.2 m up.': '高度 2.2 米。',
    '2.5 m up: the widest view.': '高度 2.5 米：视野最广。',
    '6 degrees below to 30 above.': '下 6 度至上方 30 度。',
    '10 degrees below to 35 above.': '下 10 度至上方 35 度。',
    '15 degrees below to 45 above.': '下 15 度至上方 45 度。',
    'About 31 degrees a second.': '约每秒 31 度。',
    'About 44 degrees a second.': '约每秒 44 度。',
    '37.5 degrees a second.': '每秒 37.5 度。',
    '50 degrees a second.': '每秒 50 度。',
    '52.5 degrees a second.': '每秒 52.5 度。',
    '70 degrees a second.': '每秒 70 度。',
    'A quarter more grip.': '抓地力 +25%。',
    'A quarter more pulling power.': '牵引力 +25%。',
    'A quarter quicker.': '转向快 25%。',
    'Half again as quick.': '转向快 50%。',
    'Half again the grip.': '抓地力 +50%。',
    'Half again the pulling power.': '牵引力 +50%。',
    'Twice the pulling power.': '牵引力 ×2。',
    'Castle': 'Castle',
    'UA Camo': '内衬迷彩',
    'Under Armor Camo': '内衬迷彩',
    'Armor Camo': '护甲迷彩',
    'Camo on Armor': '护甲迷彩',
    'Black ODST': '黑色 ODST',
    'Black/greys with no camo': '黑灰色，无迷彩',
    'Replaces CPG-48 Snapper': '替换 CPG-48「工兵」',
    'DP8': 'DP8',
    'RS67': 'RS67',
    'A9': 'A9',
    'Replaces medium siege ready set': '替换中型攻坚套装',
    'Replaces medium stealth set': '替换中型潜行套装',
    'Replaces helljumper set': '替换「地狱伞兵」套装',
    'Required for all replacers': '所有替换外观共用，必需',
    'Ammo Box': '弹药箱',
    'Stim Box': '兴奋剂箱',
    'Grenade Box': '手雷箱',
    'Supply Pod': '补给舱',
    'Support Weapon Pod': '支援武器舱',
    'Icon and Glow': '图标 + 光晕',
    'Icon and Glow LARGER': '图标 + 光晕（更大）',
    'Icon and Glow LODs': '图标 + 光晕（含远距 LOD）',
    'Glow Only': '仅光晕',
    'No Glow': '无光晕',
    'Static Icon': '静态图标',
    'Larger Icon Appears When Far': '远距离时显示更大图标',
    "Doesn't Support LODs Large Icon Only": '不支持远距 LOD，仅显示大图标',
    'Sentry Turrets': '哨戒炮塔',
    'Guard Dog Drones': '护卫犬无人机',
    'Smarter Guard Dogs and Sentries': '更聪明的护卫犬与哨戒炮',
    'Guard Dogs': '护卫犬',
    'Sentries': '哨戒炮',
    'All sentries': '所有哨戒炮',
    'All but the Tesla Tower': '除特斯拉塔外的所有哨戒炮',
    'Every sentry, the Tesla Tower included.': '所有哨戒炮，包括特斯拉塔。',
    'Intelligence': '智能判断',
    'Armor Intelligence and Target Prioritization': '装甲判断 + 目标优先级',
    'Only Armor Intelligence': '仅装甲判断',
    'Only Target Prioritization': '仅目标优先级',
    'Safety': '安全保护',
    'You and your teammates': '你与队友',
    'Only you': '仅你',
    'Only your teammates': '仅队友',
    'Protects you and the other players.': '保护你和其他玩家。',
    'Targeting Laser': '瞄准激光',
    'Laser Brightness': '激光亮度',
    'Normal (100%)': '正常（100%）',
    'Dim (50%)': '暗淡（50%）',
    'Softer (75%)': '柔化（75%）',
    'Bright (150%)': '明亮（150%）',
    'Brightest (200%)': '最亮（200%）',
    'The laser as it has always been.': '与原版一致的激光。',
    'Aggro Counter': '仇恨计数',
    'Position': '位置',
    'Size': '尺寸',
    'Left of the compass': '罗盘左侧',
    'Right of the compass': '罗盘右侧',
    'Under the warning banners': '警告横幅下方',
    'Nearby only': '仅附近',
    'Without nearby': '不含附近',
    'Searching + On you': '搜索中 + 锁定你',
    'Searching, on you and on teammates.': '搜索中、锁定你、锁定队友。',
    'Only the enemies that are after you.': '只统计正在追击你的敌人。',
    'When nothing is counted': '计数全为零时',
    'The counter badge. Required.': '计数器徽章。必需。',
    'Default mode': '默认模式',
    'The headlamp controller. Required.': '头灯控制器。必需。',
    'Gameplay-first flood, about 35-40 m.': '偏游戏性的泛光照明，约 35-40 米。',
    'HD2 Transmog Foundation': 'HD2 Transmog Foundation',
    'Independent armor stats (default)': '独立护甲属性（默认）',
    'Disable armor stat selection': '禁用护甲属性选择',
    'Choose look, base stats, then passive.': '依次选择外观、基础属性、被动。',
    'Helmet and cape variants': '头盔与披风变体',
    'Disable helmet and cape variants.': '禁用头盔与披风变体。',
    'Armor thumbnail passive icons': '护甲缩略图被动图标',
    'Show passive badges on armor thumbnails.': '在护甲缩略图上显示被动徽章。',
    'Tank Power': '坦克动力',
    'Tank Grip': '坦克抓地',
    'Tank Steering': '坦克转向',
    'Tank Suspension': '坦克悬挂',
    'Strong (x1.25)': '强（×1.25）',
    'Stronger (x1.5)': '更强（×1.5）',
    'Strongest (x2)': '最强（×2）',
    'Moderate (x1.25)': '中等（×1.25）',
    'Strong (x1.5)': '强（×1.5）',
    'Maximum (x2)': '最大（×2）',
    'Responsive (x1.25)': '灵敏（×1.25）',
    'Quick (x1.5)': '快速（×1.5）',
    'Sharp (x2)': '锐利（×2）',
    'Quick (x1.25)': '快速（×1.25）',
    'Fast (x1.5)': '迅捷（×1.5）',
    'Very fast (x2)': '极快（×2）',
    'Wide (-6..+30 deg)': '宽（-6..+30 度）',
    'Wider (-10..+35 deg)': '更宽（-10..+35 度）',
    'Widest (-15..+45 deg)': '最宽（-15..+45 度）',
    'Tank MBT Turrets': '坦克炮塔全向旋转',
    'Tank Turret Traverse': '炮塔回旋速度',
    'Tank Turret Elevation': '炮塔俯仰速度',
    'Tank Turret Aim Range': '炮塔俯仰范围',
    'Tank Autoloader': '坦克自动装填',
    'Gunner Drive': '炮手位驾驶',
    'Tanks and FRV': '坦克与 FRV',
    'Tanks': '坦克',
    'Tank Gunner Camera': '坦克炮手视角',
    'Close (1 m behind)': '近（后方 1 米）',
    'Far (3.5 m behind)': '远（后方 3.5 米）',
    'Farther (5.4 m behind)': '更远（后方 5.4 米）',
    'Farthest (7.4 m behind)': '最远（后方 7.4 米）',
    'Both the tanks and the M-102 FRV.': '坦克和 M-102 FRV 都启用。',
    'The M-102 FRV, from its gunner seat.': 'M-102 FRV，可在炮手座驾驶。',
    'FRV Stability': 'FRV 稳定性',
    'Vehicle Indicator': '载具指示器',
    'Minimap Settings (Map Marker)': '小地图设置（地图标记）',
    'Minimap Settings (Enemy Blips)': '小地图设置（敌人光点）',
    'Minimap Settings (View Cones)': '小地图设置（视野扇形）',
    'Compass Settings (Super Destroyer Indicator)': '罗盘设置（超级驱逐舰指示）',
    'DIAMOND (GAPPED, OUTLINED)': '菱形（间断、描边）',
    'DIAMOND (GAPPED)': '菱形（间断）',
    'DIAMOND (THICK, GAPPED, OUTLINED)': '菱形（粗、间断、描边）',
    'DIAMOND (THICK, GAPPED)': '菱形（粗、间断）',
    'DIAMOND (THICK, OUTLINED)': '菱形（粗、描边）',
    'DIAMOND (THICK)': '菱形（粗）',
    'DIAMOND (THICK, HOLLOWED, OUTLINED)': '菱形（粗、空心、描边）',
    'DIAMOND (THICK, HOLLOWED)': '菱形（粗、空心）',
    'DIAMOND (THICK, HOLLOWED, GAPPED, OUTLINED)': '菱形（粗、空心、间断、描边）',
    'DIAMOND (THICK, HOLLOWED, GAPPED)': '菱形（粗、空心、间断）',
    'HEXAGON (OUTLINED)': '六边形（描边）',
    'HEXAGON': '六边形',
    'RING (OUTLINED)': '圆环（描边）',
    'RING': '圆环',
    'POINTERS (OUTLINED)': '指针（描边）',
    'POINTERS': '指针',
    'ARROWS (OUTLINED)': '箭头（描边）',
    'ARROWS': '箭头',
    'CROSS (OUTLINED)': '十字（描边）',
    'CROSS': '十字',
    'CIRCLE (SMALL)': '圆形（小）',
    'SKULL (SMALL)': '骷髅（小）',
    'SKULL': '骷髅',
    'SUPER DESTROYER': '超级驱逐舰',
    'OUTLINED': '描边',
    'VANILLA': '原版',
    'HUD layout': 'HUD 布局',
    'Show when idle': '待机时显示',
    'Game crosshair': '游戏自带准星',
    'HD2 HUD+': 'HD2 HUD+',
    'All Mechs': '全部机甲',
    'No Muzzle Flash Smoke': '枪口无烟',
    'No Smoke Heat or Sparks - LAS 16 Sickle': '无烟、无热浪、无火花 - LAS-16 镰刀',
    'No Smoke Heat or Sparks - LAS 17 DE Sickle - Talon': '无烟、无热浪、无火花 - LAS-17 DE 镰刀 - 爪',
    'Autocannon Sentry': '机炮哨戒炮',
    'Gatling Sentry': '加特林哨戒炮',
    'Machinegun Sentry': '机枪哨戒炮',
    'Mortar Sentry': '迫击炮哨戒炮',
    'Rocket Sentry': '火箭哨戒炮',
    'Flak36': 'Flak36',
    'Flak36 (no pings)': 'Flak36（无提示音）',
    'Flak36 (quieter pings)': 'Flak36（提示音更轻）',
    'Flakm42': 'Flakm42',
    'Flakm42 (no pings)': 'Flakm42（无提示音）',
    'Flakm42 (quieter pings)': 'Flakm42（提示音更轻）',
    'KWK36': 'KWK36',
    'KWK36 (no pings)': 'KWK36（无提示音）',
    'KWK36 (quieter pings)': 'KWK36（提示音更轻）',
    '40mm bofors': '40mm 博福斯',
    'QF 2 Pounder': 'QF 2 磅炮',
    'Gau-19': 'Gau-19',
    'Gau-12': 'Gau-12',
    'M197': 'M197',
    'M61': 'M61',
    'C-RAM': 'C-RAM',
    'M134': 'M134',
    'BAR': 'BAR',
    'MG34': 'MG34',
    'MG42': 'MG42',
    'M240': 'M240',
    'MG3': 'MG3',
    'PKM': 'PKM',
    'BF1 Mortar': 'BF1 迫击炮',
    'Squad 81mm': '小队 81mm 迫击炮',
    'Malyutka': 'Malyutka',
    'Hydra': 'Hydra',
    'Menacing Recoilless Rifle': '威压 无后坐力步枪',
    'Menacing Laser Cannon': '威压 激光炮',
    'Menacing Quasar Cannon': '威压 类星体炮',
    'Menacing Autocannon': '威压 机炮',
    'Menacing Railgun': '威压 磁轨炮',
    'Menacing Epoch': '威压 Epoch',
    'Menacing Flamethrower': '威压 火焰喷射器',
    'Menacing Spear': '威压 长矛',
    'Menacing Exosuits': '威压 外骨骼',
    'Menacing HMG': '威压 重机枪',
    'Menacing Maxigun': '威压 转轮机枪',
    'Quiet Ping': '轻提示音',
    'Loud Ping': '明显提示音',
    'UnSafe Mode': '不安全模式',
    'Safe Mode': '安全模式',
    'Standard Horn': '标准号角',
    'MVM Horn': 'MvM 号角',
    '40K Horn': '40K 号角',
    'Meet The Medic': 'Meet The Medic',
    'Changes firing, idle, and repel sounds.': '替换开火、待机与驱离音效。',
    'Badge size. Fine-tune in game with Ctrl+Shift+= / -.': '徽章尺寸。游戏内可用 Ctrl+Shift+= / - 微调。',
    'Beside the compass, on its right (less room: up to about 150%).': '罗盘右侧（空间较小：最大约 150%）。',
    'Default. Beside the compass, on its left (room up to about 185%).': '默认。罗盘左侧（空间较大：最大约 185%）。',
    'Centred below the compass and the game warning banners.': '居中显示在罗盘与游戏警告横幅下方。',
    'Shrinks to fit beside the compass (about 185% on the left).': '会自动缩小以贴合罗盘（左侧约 185%）。',
    'Just the radar number: every live enemy within 60m of you.': '只显示雷达数字：你周围 60 米内的所有存活敌人。',
    'Default. Nearby, searching, on you and on teammates.': '默认。附近、搜索中、锁定你、锁定队友。',
    'Only appears when an enemy targets or searches for you or a teammate.': '仅当有敌人锁定或搜索你/队友时才出现。',
    'What the badge does while every count is 0.': '所有计数为 0 时徽章的表现。',
    'Where the badge sits. It grows away from the compass when enlarged.': '徽章所在位置。放大时会朝背离罗盘的方向扩展。',
    'Which numbers the badge shows. Other combinations: cells in the settings file.': '徽章显示哪些数字。其它组合：见设置文件中的 cells。',
    'Beside the compass: enemies near you, searching for you, targeting you, and targeting your teammates. Requires Bingus Shared Loader v18 or newer.': '在罗盘旁显示：附近的敌人、正在搜索你的敌人、锁定你的敌人，以及锁定队友的敌人。需要 Bingus Shared Loader v18 或更新版本。',
    'The guard dog and sentry improvements (safety, closest threat first, no shooting the dead, no shooting into cover, Guard Dog range, Rover fire spreading; sentries that do not fire through you or swing their fire across you, stop firing into walls, deal with enemies at their feet first, a Laser Sentry that sets enemies alight and moves on like the Rover and cools down before it burns out, and a Tesla Tower that leaves helldivers and enemies next to them alone). Keep this on.': '护卫犬与哨戒炮的整体改进（安全保护、优先最近的威胁、不射击尸体、不朝掩体开火、护卫犬射程、漫游者火焰蔓延；哨戒炮不会穿过你开火或把弹道扫过你、不会对着墙射击、优先处理脚下的敌人；激光哨戒炮能点燃敌人并像漫游者那样转移目标、过热前会先冷却；特斯拉塔不再电击绝地潜兵及其旁边的敌人）。请保持开启。',
    'The mod handles your guard dog (Guard Dog, Rover, K-9). Turn off to leave your dog to the game; your sentries and the rest of the mod keep working.': '由本模组接管你的护卫犬（护卫犬、漫游者、K-9）。关闭则护卫犬交回游戏处理，哨戒炮与本模组其它功能照常工作。',
    'The mod handles your sentries (Machine Gun, Gatling, Autocannon, Rocket, Laser, Flame, Mortar, EMS Mortar and the Tesla Tower), plus the guns on armed resupply pods and the Supply FRV. Turn off to leave your sentries to the game; your guard dog and the rest of the mod keep working.': '由本模组接管你的哨戒炮（机枪、加特林、机炮、火箭、激光、火焰、迫击炮、电磁迫击炮与特斯拉塔），以及武装补给舱和补给 FRV 上的机枪。关闭则哨戒炮交回游戏处理，护卫犬与本模组其它功能照常工作。',
    'Every sentry except the Tesla Tower, which is left to the game.': '除特斯拉塔外的所有哨戒炮（特斯拉塔交回游戏处理）。',
    'How your dogs and sentries choose what to shoot. Armor Intelligence: they leave alone armor they cannot get through (Hulks, Chargers, Tanks and similar; the Rover also Scout Striders; the Laser Sentry only what is above Heavy), fire only short bursts at Heavy Devastators, and no sentry wastes ammo on dropships (only the Rocket and Autocannon sentries shoot enemies still aboard one). Target Prioritization: your dog goes for the closest threat to you first; your sentries deal with enemies at their feet first, go for Gunships and Stingrays first (the Rocket Sentry only while one hovers), then the armor that suits the gun (Heavy for the Rocket and Autocannon, lighter for the Machine Gun, Gatling and Laser; the closest first for the Flame Sentry). Turn off to leave both to the game. Everything else keeps working.': '决定护卫犬与哨戒炮如何选择目标。装甲判断：跳过打不穿的装甲（浩克、冲锋虫、坦克等；漫游者还会跳过侦察追猎者；激光哨戒炮只打重型以上），对重型破坏者只点射，且没有哨戒炮会把弹药浪费在运输艇上（只有火箭与机炮哨戒炮会射击仍在艇上的敌人）。目标优先级：护卫犬优先攻击离你最近的威胁；哨戒炮优先处理脚下的敌人，其次优先炮艇与黄貂鱼（火箭哨戒炮只在悬停时），再按武器特性选择装甲（火箭与机炮打重型、机枪/加特林/激光打轻型；火焰哨戒炮优先最近）。关闭则两者都交回游戏，其余功能照常。',
    'Skip armor they cannot hurt and dropships; the game decides the order.': '跳过打不动的装甲和运输艇；攻击顺序由游戏决定。',
    'The right target first; they may shoot armor they cannot hurt.': '优先攻击正确的目标；可能对打不动的装甲开火。',
    'Who your dog and your sentries never fire through: they hold fire while that helldiver is in their line of fire, do not swing their fire across them, mortars and the rocket sentry leave enemies next to them alone, and the Tesla Tower does not zap them or arc into them. Turn off at your own risk: they will fire through anyone. Everything else keeps working.': '决定护卫犬与哨戒炮绝不穿过谁开火：当该绝地潜兵处于弹道上时停火、不把弹道扫过他们、迫击炮与火箭哨戒炮不攻击其身边的敌人、特斯拉塔不电击也不对其电弧。关闭需自行承担风险：它们会穿过任何人开火。其余功能照常。',
    'Protects the other players; they may fire through you.': '保护其他玩家；可能穿过你开火。',
    'Protects you; they may fire through other players.': '保护你；可能穿过其他玩家开火。',
    'Laser out of the barrel of your guard dog and your sentries (not the mortars) toward their targets, shown only on your screen: green while they fire, flashing red when the safety stops a shot (and a red ring around the rocket sentry while an enemy is too close for it to fire), flashing yellow when the dog target goes out of sight (cover or smoke), off while the dog reloads. The Tesla Tower shows its reach as a yellow ring instead. Turn off to hide it.': '从护卫犬与哨戒炮（迫击炮除外）枪口射向目标的激光，只在你屏幕上显示：开火时为绿色，安全保护拦下射击时闪红（敌人离火箭哨戒炮太近时它会显示红圈），护卫犬目标被掩体或烟雾遮挡时闪黄，装填时熄灭。特斯拉塔改以黄色圆环显示作用范围。关闭即隐藏。',
    'A thin, plain line with a small cross where it hits. Simple to look at, but walls and objects hide it.': '细直线，命中处有小十字。观感简洁，但会被墙壁和物体遮挡。',
    'A soft glowing beam with a bright spot on the target. It looks much better than the line, but it shows through walls and objects (the game draws it on top of the world).': '柔和光晕光束，命中点亮起光斑。比细线好看得多，但会穿透墙壁与物体（游戏把它绘制在世界之上）。',
    'How bright the targeting laser is: its beams and rings, line or glow.': '瞄准激光的亮度：包括光束与圆环、线状或光晕。',
    'The laser at 50% of its normal brightness.': '亮度为正常值 50% 的激光。',
    'The laser at 75% of its normal brightness.': '亮度为正常值 75% 的激光。',
    'The laser at 150% of its normal brightness.': '亮度为正常值 150% 的激光。',
    'The laser at 200% of its normal brightness.': '亮度为正常值 200% 的激光。',
    'Short-range helmet task light, about 20-25 m.': '近距离头盔作业灯，约 20-25 米。',
    'Initial mode; the mode key still switches it.': '初始模式；模式键仍可切换。',
    'Customise the appearance of the map marker.': '自定义地图标记的外观。',
    'Customise the appearance of the enemy blips (the solid red circles on the map which show enemy unit positions).': '自定义敌人光点的外观（地图上表示敌军位置的红色实心圆）。',
    'Customise the appearance of Helldiver view cones on the minimap.': '自定义小地图上绝地潜兵视野扇形的外观。',
    'Customise the appearance of the Super Destroyer compass indicator.\n(NOTE: This is only enabled in megacity missions.)': '自定义超级驱逐舰罗盘指示器的外观。\n（注意：仅在巨型城市任务中启用。）',
    'Body-armor creation process. Helmet/cape and icon settings are independent.': '护甲创建流程。头盔/披风与图标设置相互独立。',
    'Choose look and passive; the look supplies base stats.': '选择外观与被动；基础属性由外观决定。',
    'Shared variant creator for detected helmet/cape passives. On by default.': '为识别到的头盔/披风被动提供共享的变体创建器。默认开启。',
    'Use the same + creator for helmets and capes with detected gameplay changes.': '对检测到玩法变化的头盔与披风，使用同一个「+」创建器。',
    'Show or hide passive badges on armor thumbnails. On by default.': '在护甲缩略图上显示或隐藏被动徽章。默认开启。',
    'Hide thumbnail badges; passive-selection and detail-panel icons stay visible.': '隐藏缩略图上的徽章；被动选择界面与详情面板的图标仍然显示。',
    'More pulling power for the Bastion and Maelstrom: quicker off the line and up slopes. Top speed is unchanged.': '提升堡垒与漩涡的牵引力：起步与爬坡更快。最高速度不变。',
    'More track grip for the Bastion and Maelstrom: less sliding on slopes and in turns.': '提升堡垒与漩涡的履带抓地力：在斜坡与转弯时更少打滑。',
    'Quicker steering for the Bastion and Maelstrom: they start and stop turning sooner.': '提升堡垒与漩涡的转向响应：起转与停转都更快。',
    'Road wheels that work like a tank: the game tanks rest on their bump stops, so the wheels cannot move. Here each wheel rests part-way down a longer travel and follows the ground, keeping its track down, well damped; the hull is no longer thrown sideways when one track unloads. The tanks ride a little higher than in the game.': '像真实坦克那样工作的负重轮：原版坦克压在缓冲块上，轮子无法活动。本模组让每个轮子在更长的行程中半悬并贴合地面，履带始终压地、阻尼充分；单侧履带卸载时车体不再被甩向一侧。车体会比原版略高一点。',
    'Half a metre of wheel travel, each wheel resting half-way: soaks up rough ground; the hull resists being rolled and the grip is shared between the tracks.': '轮行程半米、每个轮子停在中间位置：能吸收崎岖地面；车体不易被翻覆，抓地力由两侧履带共同承担。',
    'Stiffer, more damped wheels with a little less travel; the hull is very hard to roll and the tracks share almost all the grip.': '轮子更硬、阻尼更强、行程略短；车体极难翻覆，几乎全部抓地力由履带承担。',
    'The Bastion and Maelstrom turrets turn all the way round like a main battle tank. The Maelstrom missile pods and smoke launchers turn with it. Only you see the new turrets, and their armor always looks undamaged.': '堡垒与漩涡的炮塔可像主战坦克那样 360 度旋转。漩涡的导弹发射巢与烟雾发射器随之转动。新炮塔只有你自己能看到，且其装甲始终显示为完好。',
    'How fast the Bastion and Maelstrom turrets turn (the game: 25 degrees a second). Works with or without MBT Turrets.': '堡垒与漩涡炮塔的转速（原版：每秒 25 度）。无论是否开启「炮塔全向旋转」都有效。',
    'How fast the Bastion and Maelstrom guns move up and down (the game: 35 degrees a second).': '堡垒与漩涡火炮的俯仰速度（原版：每秒 35 度）。',
    'How far down and up the Bastion and Maelstrom guns aim (the game: 3 below to 25 above).': '堡垒与漩涡火炮的俯仰范围（原版：下 3 度至上 25 度）。',
    'The Bastion and Maelstrom main gun reloads by itself when it runs dry, at the normal reload speed (perks count). You can still reload by hand.': '堡垒与漩涡的主炮打空后会自动装填，速度为正常装填速度（受相关加成影响）。仍可手动装填。',
    'Drive from the gunner seat when the driver seat is empty: your movement keys drive, the gun works as normal, and a driver panel shows gear, rpm, speed and fuel. F sounds the horn; in the Maelstrom, Mouse 3 pops smoke. On a controller the left stick drives, its click sounds the horn and the right stick click pops smoke. A teammate who takes the wheel drives as normal, and getting out while it rolls brakes it to a stop. With the Mod Bindings Menu you can set your own keys (controls, tab MODS). Pick which vehicles.': '驾驶位空置时可在炮手座驾驶：移动键控制行驶，武器照常工作，并显示档位、转速、速度与燃料面板。按 F 鸣笛；漩涡上鼠标中键释放烟雾。手柄用左摇杆驾驶、按下鸣笛、右摇杆按下放烟雾。队友接方向盘后按正常方式驾驶；行驶中下车会自动刹停。配合「模组按键菜单」可自定义按键（控制设置里的 MODS 分页）。可选择适用于哪些载具。',
    'Puts the Bastion and Maelstrom gunner camera lower and further back so you see more around the tank. It stays behind the turret as it turns.': '把堡垒与漩涡的炮手视角放得更低更靠后，便于观察坦克周围。视角会始终跟随炮塔后方。',
    'The game distance, 1.4 m up (the game: 2 m).': '与原版一致的距离，高度 1.4 米（原版为 2 米）。',
    'Keeps the M-102, M-103 and M-104 FRVs on their wheels over rough ground, jumps and hard turns: a firmer front, longer suspension travel, a lower center of mass, more grip and weight, and a little more ground clearance. Engine and steering stay the game own.': '让 M-102、M-103、M-104 FRV 在崎岖地面、跳跃与急转弯时保持四轮着地：前悬更硬、悬挂行程更长、重心更低、抓地与重量更高，离地间隙略增。引擎与转向保持原版。',
    'Half the change: still lively, far less likely to roll.': '改动一半：依然灵活，但翻车概率大幅降低。',
    'Stays upright over rough ground, jumps and hard turns; a quarter heavier.': '在崎岖地面、跳跃与急转弯时保持直立；重量增加四分之一。',
    'Lower, grippier, stiffer and 40% heavier, and the chassis resists rolling: very hard to tip, slower to turn.': '更低、更抓地、更硬且重量 +40%，车架抗翻覆：极难翻车，但转向变慢。',
    'A small outline of your vehicle shows where the gun points compared to the hull, colored by health (blue to red). Works in the Bastion, the Maelstrom, the M-102 FRV and the M-103 Supply FRV, in any seat; the FRVs tires each show their own health and go clear when popped. Only you see it.': '屏幕上的载具小轮廓显示炮口相对车体的朝向，颜色随耐久变化（蓝到红）。堡垒、漩涡、M-102 FRV、M-103 补给 FRV 的任意座位均可用；FRV 的每个轮胎单独显示耐久，爆胎后变透明。只有你自己能看到。',
    'Required for the HUD to work. Keep this enabled and use the options below to choose what is displayed.': 'HUD 运行所必需。请保持启用，并在下面选择要显示的内容。',
    'Enabled by default. Choose one: Integrated / Rings / Simple.': '默认开启。三选一：一体化 / 圆环 / 简洁。',
    'Under the crosshair: a charge, reload, heat or rounds arc, ammo, reserve ammo, health/stamina bars, stims, throwables, backpack. Best with game HUD on Map only.': '准星下方：充能/装填/热量/弹数弧线、弹药、备弹、生命与耐力条、兴奋剂、投掷物、背包。建议把游戏 HUD 设为「仅地图」。',
    'A ring by the crosshair shows charge, reload, heat or rounds; another shows a backpack own resource. Plus ammo, reserve ammo and weapon setting icons.': '准星旁的一个圆环显示充能、装填、热量或弹数；另一个圆环显示背包资源。另含弹药、备弹与武器状态图标。',
    'Weapon setting icons only - fire mode, function, scope zoom - beside the game weapon panel. Fixed brightness, and they hide when that panel hides.': '只显示武器状态图标（射击模式、功能、倍镜）在游戏武器面板旁。亮度固定，随该面板一同隐藏。',
    'Enabled by default. Choose one: Faint / Full brightness.': '默认开启。二选一：微弱 / 全亮。',
    'Dims the crosshair HUD to 30% brightness when idle. Does not affect Simple or squad icons.': '待机时把准星 HUD 亮度降到 30%。不影响「简洁」模式与小队图标。',
    'Keeps the crosshair HUD at full brightness when idle. Does not affect Simple or squad icons.': '待机时保持准星 HUD 全亮。不影响「简洁」模式与小队图标。',
    'Each squad row shows that player booster, yours last - a skull while that player is dead, or what they just pinged. Stratagems they call stack along the row. All hide with it.': '小队每行显示该玩家的增益（你自己在最后）——该玩家阵亡时显示骷髅，或显示他刚标记的内容。他们呼叫的战略配备会沿该行堆叠。整块显示可一并隐藏。',
    'The stratagems you chose, on a row at the bottom center: each drains on the way in, fills back as it cools, shows uses left while ready, carries a soft tint of its in-game colour while ready that turns full and enlarges while its beacon is out, and goes grey when the game blocks it.': '你选择的战略配备，排列在屏幕底部中央：呼叫时逐渐消耗、冷却时回填、就绪时显示剩余次数；就绪时带有其游戏内颜色的淡色标记，信标投放期间变为实色并放大；被游戏禁用时变灰。',
    'Lets the game draw its own crosshair for the Anti-Materiel Rifle in third person and the Maxigun in first person. It follows the game crosshair setting.': '让游戏为第三人称的反器材步枪与第一人称的转轮机枪绘制自带准星。跟随游戏的准星设置。',
    'Removes the smoke from firing a weapon while keeping the muzzle flash.': '移除开火时的硝烟，同时保留枪口火光。',
    'Enhances the sounds of the Sentries': '强化哨戒炮的音效',
    'Changes firing, shell eject, and shell impact sounds.': '替换开火、抛壳与炮弹命中音效。',
    'Changes charge-up, firing, and overheat alarm sounds.': '替换充能、开火与过热警报音效。',
    'Changes charge-up, firing, cooldown, and ready-state sounds.': '替换充能、开火、冷却与就绪状态音效。',
    'Changes firing, reload (with ping), and gun open/close sounds.': '替换开火、装填（含提示音）与炮闩开合音效。',
    'A subtle, low-volume ping heard while shooting.': '射击时能听到的轻微、低音量提示音。',
    'A distinct, much louder ping heard while shooting.': '射击时能听到的明显、音量更大的提示音。',
    'Changes firing, reload, and charge-up sounds, including safety mode alerts.': '替换开火、装填与充能音效，并包含安全模式提示音。',
    'Includes an alarm to warn you when you are about to explode.': '包含即将过载爆炸时的警报音。',
    'Includes a sound cue for reaching maximum safe charge.': '包含达到最大安全充能时的提示音。',
    'Combines Unsafe and Safe sounds. Note: Slightly less immersive due to overlapping cues.': '同时包含「不安全」与「安全」音效。注意：提示音重叠，代入感略降。',
    'Changes firing, charge-up, and reload sounds; adds a warning as you near max charge.': '替换开火、充能与装填音效；接近最大充能时增加警告音。',
    'Changes firing, lock-on, and target-locked sounds.': '替换开火、锁定与锁定完成音效。',
    'Changes enter/exit, movement, engine, and stomp sounds for Patriot and Emancipator.': '替换爱国者与解放者的进出舱、移动、引擎与踏步音效。',
    'The default menacing horn sound for the Exosuit.': '外骨骼默认的威压号角声。',
    'The iconic mechanical roar of the MvM Tank from Team Fortress 2.': '《军团要塞 2》中 MvM 坦克标志性的机械咆哮。',
    'The iconic Warlord Titan Warhorn from the 40K universe.': '40K 世界观中战将泰坦标志性的战争号角。',
    'Doctor! Are you sure this will work? Ha ha ha, I have no idea!': '医生！你确定这能行？哈哈哈，我完全不知道！',
    'Changes firing, wind-up/down and spin-loop audio.': '替换开火、加速/减速与旋转循环音效。',
    'Changes the firing sound (more updates planned).': '替换开火音效（后续还会继续更新）。',
    'ARSENAL: place this loader LAST (bottom of the list) with default priority, or FIRST if first-mod priority is enabled. Required by Armory Preview Cache, Know Your Constellation, Controllable Hover Pack, Vehicle Stability, Enemy Collision Synchronized, Vanilla Plus Megapack or the separate Better Stratagem Bounce, Hellpod Steering Unlocked, Reinforcement Beacons Fixed, Consistent Vaulting, Shallow Water Diving and Sentry Aim Retention mods. Import this ZIP through Arsenal or HD2MM, enable it alongside the megapack or your chosen mods, then Deploy. Also supports HUD Ballistic Trajectory Overlay v2.': 'Arsenal 用法：把本加载器放在列表最后（默认优先级），或在使用「首个模组优先」时放在最前。以下模组需要它：军械库预览缓存、敌情预测、悬浮背包可控下降、载具稳定性、敌人碰撞同步修正、Vanilla Plus 合集，或单独的「战备球弹射优化」「地狱舱转向解锁」「增援信标修正」「翻越判定稳定化」「浅水区飞扑」「哨戒炮瞄准保持」。请用 Arsenal 或 HD2MM 导入本 ZIP，与合集或你选的模组一起启用，然后 Deploy。同时支持「HUD 弹道轨迹叠加 v2」。',
    'Builds 25327279, 25480438 only. GL-52 owner exclusion; damage and range unchanged. Unknown game modules stop safely. Requires Bingus Shared Loader v15+ / API 1 and discovery.': '仅支持 25327279、25480438 版本。GL-52 排除发射者自身；伤害与射程不变。遇到未知游戏模块会安全停止。需要 Bingus Shared Loader v15+ / API 1 与 discovery。',
    '(v3.0.6) Redesigned, clear and precise map markers.': '（v3.0.6）重新设计，地图标记更清晰精准。',
    "A ring by the crosshair shows charge, reload, heat or rounds; another shows a backpack's own resource. Plus ammo, reserve ammo and weapon setting icons.": '准星旁的一个圆环显示充能、装填、热量或弹数；另一个显示背包自身资源。另含弹药、备弹与武器状态图标。',
    'All-in-one file; choose which weapon sounds you want to use.': '整合包：自行选择要使用哪些武器音效。',
    'Ammo, reload, charge, backpack, health and stratagems - read them without looking away from your target.': '弹药、装填、充能、背包、生命与战略配备——不必移开视线就能看清。',
    'Bastion, Maelstrom and FRV upgrades, each its own option: tank power, grip, steering and suspension; 360-degree MBT turrets with traverse, elevation and aim range; an autoloader; driving from the gunner seat; gunner camera distance; FRV stability; and a vehicle indicator. With the Mod Options Menu, the options can be changed in game. Requires Bingus Shared Loader.': '堡垒、漩涡与 FRV 的升级，每项独立可选：坦克动力、抓地、转向与悬挂；360 度主战坦克炮塔（含回旋、俯仰与俯仰范围）；自动装填；炮手座驾驶；炮手视角距离；FRV 稳定性；载具指示器。配合「模组选项菜单」可在游戏内调整。需要 Bingus Shared Loader。',
    'Beside the compass: enemies near you, searching for you, targeting you, and targeting your teammates. Requires Bingus Shared Loader v15 or newer / API 1.': '在罗盘旁显示：附近的敌人、正在搜索你的敌人、锁定你的敌人，以及锁定队友的敌人。需要 Bingus Shared Loader v15 或更新版本 / API 1。',
    "Customise the appearance of the enemy 'blips' (the solid red circles on the map which show enemy unit positions).": '自定义敌人光点的外观（地图上表示敌军位置的红色实心圆）。',
    "Each squad row shows that player's booster, yours last - a skull while that player is dead, or what they just pinged. Stratagems they call stack along the row. All hide with it.": '小队每行显示该玩家的增益（你自己在最后）——该玩家阵亡时显示骷髅，或显示他刚标记的内容。他们呼叫的战略配备会沿该行堆叠。整块显示可一并隐藏。',
    "How your dogs and sentries choose what to shoot. Armor Intelligence: they leave alone armor they can't get through (Hulks, Chargers, Tanks and similar; the Rover also Scout Striders; the Laser Sentry only what is above Heavy), fire only short bursts at Heavy Devastators, and no sentry wastes ammo on dropships (only the Rocket and Autocannon sentries shoot enemies still aboard one). Target Prioritization: your dog goes for the closest threat to you first; your sentries deal with enemies at their feet first, go for Gunships and Stingrays first (the Rocket Sentry only while one hovers), then the armor that suits the gun (Heavy for the Rocket and Autocannon, lighter for the Machine Gun, Gatling and Laser; the closest first for the Flame Sentry). Turn off to leave both to the game. Everything else keeps working.": '决定护卫犬与哨戒炮如何选择目标。装甲判断：跳过打不穿的装甲（浩克、冲锋虫、坦克等；漫游者还会跳过侦察追猎者；激光哨戒炮只打重型以上），对重型破坏者只点射，且没有哨戒炮会把弹药浪费在运输艇上（只有火箭与机炮哨戒炮会射击仍在艇上的敌人）。目标优先级：护卫犬优先攻击离你最近的威胁；哨戒炮优先处理脚下的敌人，其次优先炮艇与黄貂鱼（火箭哨戒炮只在悬停时），再按武器特性选择装甲（火箭与机炮打重型、机枪/加特林/激光打轻型；火焰哨戒炮优先最近）。关闭则两者都交回游戏，其余功能照常。',
    "Keeps the M-102, M-103 and M-104 FRVs on their wheels over rough ground, jumps and hard turns: a firmer front, longer suspension travel, a lower center of mass, more grip and weight, and a little more ground clearance. Engine and steering stay the game's own.": '让 M-102、M-103、M-104 FRV 在崎岖地面、跳跃与急转弯时保持四轮着地：前悬更硬、悬挂行程更长、重心更低、抓地与重量更高，离地间隙略增。引擎与转向保持原版。',
    "Laser out of the barrel of your guard dog and your sentries (not the mortars) toward their targets, shown only on your screen: green while they fire, flashing red when the safety stops a shot (and a red ring around the rocket sentry while an enemy is too close for it to fire), flashing yellow when the dog's target goes out of sight (cover or smoke), off while the dog reloads. The Tesla Tower shows its reach as a yellow ring instead. Turn off to hide it.": '从护卫犬与哨戒炮（迫击炮除外）枪口射向目标的激光，只在你屏幕上显示：开火时为绿色，安全保护拦下射击时闪红（敌人离火箭哨戒炮太近时它会显示红圈），护卫犬目标被掩体或烟雾遮挡时闪黄，装填时熄灭。特斯拉塔改以黄色圆环显示作用范围。关闭即隐藏。',
    "Lets the game draw its own crosshair for the Anti-Materiel Rifle in third person and the Maxigun in first person. It follows the game's crosshair setting.": '让游戏为第三人称的反器材步枪与第一人称的转轮机枪绘制自带准星。跟随游戏的准星设置。',
    'Owned armor, helmet and cape variants with independent appearance, stats and exact passives. Requires Bingus Shared Loader v15 or newer (API 1). Native stat/perk previews and one-button equipment in the Armor list. Create saves locally without equipping the armor.': '已拥有的护甲、头盔与披风变体，外观、属性与被动完全独立。需要 Bingus Shared Loader v15 或更新版本（API 1）。护甲列表内提供原生属性/被动预览与一键装备。可在不装备护甲的情况下本地创建存档。',
    'Recplaces all mechs with the concept mech': '把所有机甲替换为概念机甲',
    'Red or green laser sights on the six sentry turrets and the five Guard Dog drones, so you can see where they are aiming.': '为六种哨戒炮与五种护卫犬无人机加上红色或绿色激光瞄准，便于看清它们的射击方向。',
    'Replaces CPG-48 Snapper, Includes 3 camo options': '替换 CPG-48「工兵」，含 3 种迷彩选项',
    'Replaces DP-8 or RS-67 with custom reach style ODST': '把 DP-8 或 RS-67 替换为自定义的致远星风格 ODST',
    "Road wheels that work like a tank's: the game's tanks rest on their bump stops, so the wheels can't move. Here each wheel rests part-way down a longer travel and follows the ground, keeping its track down, well damped; the hull is no longer thrown sideways when one track unloads. The tanks ride a little higher than in the game.": '像真实坦克那样工作的负重轮：原版坦克压在缓冲块上，轮子根本无法活动。本模组让每个轮子在更长的行程中半悬并贴合地面，履带始终压地、阻尼充分；单侧履带卸载时车体不再被甩向一侧。车体会比原版略高一点。',
    "Skip armor they can't hurt and dropships; the game decides the order.": '跳过打不动的装甲和运输艇；攻击顺序由游戏决定。',
    "Smarter, safer aiming for your guard dog (Guard Dog, Rover, K-9), your sentries and the resupply pod and Supply FRV guns. They never shoot through you or your teammates, skip the dead, cover and armor they can't hurt, and pick the right targets. The Tesla Tower stops zapping you. Optional targeting laser. Each part can be turned on or off in the options (also in game with Mod Options Menu). Requires Bingus Shared Loader v15 or newer.": '让护卫犬（护卫犬、漫游者、K-9）、哨戒炮以及补给舱和补给 FRV 的机枪瞄得更聪明、更安全。它们绝不穿过你或队友开火，跳过尸体、掩体和打不动的装甲，并选出正确的目标。特斯拉塔不再电击你。可选瞄准激光。每个部分都能在选项里单独开关（也可在游戏内「模组选项菜单」里调整）。需要 Bingus Shared Loader v15 或更新版本。',
    'The Bastion and Maelstrom, from the gunner seat.': '堡垒与漩涡，可在炮手座驾驶。',
    "The game's distance, 1.4 m up (the game: 2 m).": '与原版一致的距离，高度 1.4 米（原版为 2 米）。',
    "The guard dog and sentry improvements (safety, closest threat first, no shooting the dead, no shooting into cover, Guard Dog range, Rover fire spreading; sentries that don't fire through you or swing their fire across you, stop firing into walls, deal with enemies at their feet first, a Laser Sentry that sets enemies alight and moves on like the Rover and cools down before it burns out, and a Tesla Tower that leaves helldivers and enemies next to them alone). Keep this on.": '护卫犬与哨戒炮的整体改进（安全保护、优先最近的威胁、不射击尸体、不朝掩体开火、护卫犬射程、漫游者火焰蔓延；哨戒炮不会穿过你开火或把弹道扫过你、不会对着墙射击、优先处理脚下的敌人；激光哨戒炮能点燃敌人并像漫游者那样转移目标、过热前会先冷却；特斯拉塔不再电击绝地潜兵及其旁边的敌人）。请保持开启。',
    "The right target first; they may shoot armor they can't hurt.": '优先攻击正确的目标；可能对打不动的装甲开火。',
    'Toggleable helmet flood light with two switchable profiles. L toggles, N switches mode while the lamp is on; both keys are rebindable in the ini, or in game with Mod Bindings Menu v2. The hotkeys are ignored while the in-game chat box is open. Requires Bingus Shared Loader v15 or newer.': '可开关的头盔泛光灯，带两套可切换配置。按 L 开关，开灯时按 N 切换模式；两个按键都可在 ini 里重绑，也可用游戏内的「模组按键菜单 v2」重绑。游戏内聊天框打开时热键会被忽略。需要 Bingus Shared Loader v15 或更新版本。',
    'Twice as quick: the tanks snap into turns.': '转向快一倍：坦克入弯干脆利落。',
    'Twice the grip: the tanks stick to the ground.': '抓地力翻倍：坦克稳稳咬地。',
    "Visibility Boost when you're in need!": '危难时刻，看得更清！',
    "Weapon setting icons only - fire mode, function, scope zoom - beside the game's weapon panel. Fixed brightness, and they hide when that panel hides.": '只显示武器状态图标（射击模式、功能、倍镜）于游戏武器面板旁。亮度固定，随该面板一同隐藏。',
    'Aggro Counter v1.3': '仇恨计数 v1.3',
    'Armored Overhaul 3.0.1': '装甲大修 3.0.1',
    'Better Map Markers': '更好的地图标记',
    'Bingus Shared Loader - v18': 'Bingus 共享加载器 - v18',
    'Castle ODST': 'Castle ODST',
    'Concept Mech': '概念机甲',
    'Enhanced Sentries Revamped': '强化哨戒炮重制版',
    'GL-52 Shooter Exclusion v0.1.2': 'GL-52 射击者排除 v0.1.2',
    'Glowing Supply Icons v4.2': '发光补给图标 v4.2',
    'Helmet Headlamp': '头盔头灯',
    'Menacing Heavy Weapons - 1.7.4': '威压重型武器 - 1.7.4',
    'Muzzle Flash Smoke Remover 3.2.2': '枪口硝烟移除 3.2.2',
    'ODST Loner': 'ODST 独行者',
    'Smarter Guard Dogs & Sentries 4.6.1': '更聪明的护卫犬与哨戒炮 4.6.1',
    'Super Laser Sights for Turrets and Drones': '炮塔与无人机激光瞄准',
    'Vanilla Plus Megapack - v35': 'Vanilla Plus 合集 - v35',
    'GNH Transmog 界面汉化（可选）': 'GNH Transmog 界面汉化（可选）',
    'GNH 简体中文汉化包': 'GNH 简体中文汉化包',
    'Mod Bindings Menu v2.1': '模组按键菜单 v2.1',
    'Mod Bindings Menu': '模组按键菜单',
    'Native MODS tab for mod bindings': '用于模组按键的原生 MODS 分页',
    'Adds a native MODS tab to the keyboard and controller binding pages: up to 36 mod bindings grouped by mod, with every activation type and controller buttons. Requires Bingus Shared Loader v17+.': '在键盘与控制器按键设置页新增原生「MODS」分页：最多 36 个模组按键，按模组分组，支持所有触发方式与手柄按键。需要 Bingus Shared Loader v17+。',
    'ARES - Official Arsenal Mod': 'ARES - Arsenal 官方模组',
    'Replaces AD-26 Armor, B-01 Helmet, CE-81 Armor, and CE-81 Helmet with Commander Ares, the Arsenal Mod Manager mascot character. Includes multiple visor options for the helmets.': '把 AD-26 护甲、B-01 头盔、CE-81 护甲与 CE-81 头盔替换为 Arsenal 模组管理器的吉祥物角色「指挥官 ARES」。头盔含多种面罩样式。',
    'AD-26 // Armor': 'AD-26 // 护甲',
    'Replaces AD-26 Armor': '替换 AD-26 护甲',
    'B-01 // Helmet': 'B-01 // 头盔',
    'Replaces B-01 Helmet': '替换 B-01 头盔',
    'CE-81 // Armor': 'CE-81 // 护甲',
    'Replaces CE-81 Armor': '替换 CE-81 护甲',
    'CE-81 // Helmet': 'CE-81 // 头盔',
    'Replaces CE-81 Helmet': '替换 CE-81 头盔',
    'Gold Shark Visor': '金色鲨鱼面罩',
    'Gold Visor': '金色面罩',
    'Silver Shark Visor': '银色鲨鱼面罩',
    'Silver Visor': '银色面罩',
    'Nightfall Operator Body Armors (B-01) (Original)': '暗夜行动员护甲（B-01）（原版）',
    'FRV Anti-Flip': 'FRV 防翻车',
    'HD2 SmoothBoot': 'HD2 平滑启动',
    'Requires Bingus Shared Loader v15 or newer / API 1. Enable both and deploy.': '需要 Bingus Shared Loader v15 或更新版本 / API 1。两者都启用后部署。',
    'HD2 C4 Quick Actions 1.13': 'HD2 C4 快捷操作 1.13',
    'C4 throw and detonate actions with customizable mouse and controller bindings, Manual/Contact detonation modes, passenger throwing and automatic reload. Requires Mod Bindings Menu v2 and Bingus Shared Loader v17+.': 'C4 投掷与引爆操作，可自定义鼠标与手柄按键；含手动/接触两种引爆模式、载员投掷与自动装填。需要「模组按键菜单 v2」与 Bingus Shared Loader v17+。',
    'Objective Tracker': '目标追踪器',
    'Locate side objectives, enemy installations and specimen samples with clear icons, live distances and compass directions. Completed objectives disappear automatically as the game confirms them. Customize the panel position, size, transparency, colors and target filters. Choose to keep the panel visible or show it only with the tactical map. See who is carrying a head, egg or larva with squad tags beside the item.': '用清晰的图标、实时距离与罗盘方位定位支线目标、敌人设施与样本。目标完成后会随游戏确认自动消失。可自定义面板位置、大小、透明度、颜色与目标筛选；可选择常驻显示，或只在战术地图上显示。物品旁的小队标记会显示谁拿着头颅、虫卵或幼虫。',
    'Smarter Guard Dogs & Sentries 4.6.3': '更聪明的护卫犬与哨戒炮 4.6.3',
    'HD2 Transmog Foundation 0.2.1 (Experimental)': 'HD2 Transmog 基础组件 0.2.1（实验版）',
    'HD2 Transmog Foundation 0.2.0 (Alpha)': 'HD2 Transmog 基础组件 0.2.0（Alpha）',
    'Show Badge': '显示徽章',
    'Show the badge beside the compass. Same as Ctrl+Shift+O.': '在罗盘旁显示徽章。同 Ctrl+Shift+O。',
    'Where the badge sits. Beside the compass it grows away from it when enlarged.': '徽章所在位置。放大时会向背离罗盘的方向扩展。',
    'Left of Compass': '罗盘左侧',
    'Right of Compass': '罗盘右侧',
    'Under Warning Banners': '警告横幅下方',
    'Badge size. It shrinks by itself if it does not fit beside the compass.': '徽章尺寸。若罗盘旁放不下会自动缩小。',
    'Move Right': '向右移动',
    'Nudge the badge sideways, in 1440p pixels (negative = left). Same as Ctrl+Shift+J / L.': '左右微调徽章，单位 1440p 像素（负值 = 向左）。同 Ctrl+Shift+J / L。',
    'Move Down': '向下移动',
    'Nudge the badge up or down, in 1440p pixels (negative = up). Same as Ctrl+Shift+I / K.': '上下微调徽章，单位 1440p 像素（负值 = 向上）。同 Ctrl+Shift+I / K。',
    'Nearby Cell': '附近计数',
    'Radar: every live enemy within the nearby radius of you, whatever it is doing.': '雷达：附近半径内所有存活敌人，无论它在做什么。',
    'Searching Cell': '搜索计数',
    'Eye: enemies searching for you (lost sight of you, alerted, dropping in, emerging).': '眼睛：正在搜索你的敌人（跟丢你、进入警戒、空降、钻出地面）。',
    'On You Cell': '锁定你',
    'Reticle: enemies fighting you, or the vehicle you are in.': '准星：正在攻击你或你所乘载具的敌人。',
    'Teammates Cell': '锁定队友',
    'People: enemies fighting your teammates.': '人物：正在攻击你队友的敌人。',
    'When Nothing Is Counted': '计数全为零时',
    'What the badge does while every shown number is 0.': '所有显示数字均为 0 时，徽章的表现。',
    'Background Opacity': '背景不透明度',
    'Red From': '变红阈值',
    'Enemies on you from which the on-you number and bar turn red.': '锁定你的敌人达到该数量时，「锁定你」的数字与进度条变红。',
    'Nearby Radius (m)': '附近半径（米）',
    'How far the nearby cell counts enemies.': '附近计数统计敌人的最远距离。',
    'Ctrl+Shift Keys': 'Ctrl+Shift 快捷键',
    'The Ctrl+Shift keys that show, resize and move the badge.': '用于显示、缩放和移动徽章的 Ctrl+Shift 快捷键。',
    'Let HUD Mods Replace It': '允许 HUD 模组接管',
    'Another HUD mod may hide this badge while it shows the same numbers itself.': '其他 HUD 模组可隐藏此徽章，改由它自己显示相同数字。',
    'Diagnostic Log': '诊断日志',
    'Detailed log (Logs/AggroCounter.log) for bug reports; F8 then marks the moment. Leave it off otherwise.': '用于反馈问题的详细日志（Logs/AggroCounter.log）；F8 可标记当前时刻。平时请保持关闭。',
    'ARMORED OVERHAUL': '装甲大修',
    "The Bastion and Maelstrom turrets turn all the way round like a main battle tank. The Maelstrom's missile pods and smoke launchers turn with it. Only you see the new turrets, and their armor always looks undamaged.": '堡垒与漩涡的炮塔可像主战坦克一样整圈旋转，漩涡的导弹发射巢与烟雾发射器会随之转动。新炮塔只有你能看到，且其装甲始终显示为未受损。',
    "Drive from the gunner seat when the driver seat is empty: your movement keys drive and a driver panel shows gear, rpm, speed and fuel. F sounds the horn; Mouse 3 pops the Maelstrom's smoke. Controller: the left stick drives, its click is the horn, the right stick click pops smoke. Set your own keys with the Mod Bindings Menu. A teammate who takes the wheel drives. Pick which vehicles.": '驾驶座无人时可从炮手座驾驶：用移动键开车，并显示档位、转速、速度与燃料的驾驶面板。F 鸣笛；鼠标中键释放漩涡的烟雾。手柄：左摇杆驾驶，按下左摇杆鸣笛，按下右摇杆放烟。可用 Mod Bindings Menu 自定义按键。队友上车驾驶时由队友操控。可选择适用载具。',
    'FRV': 'FRV',
    "A small outline of your vehicle shows where the gun points compared to the hull, colored by health (blue to red). Works in the Bastion, the Maelstrom, the M-102 FRV and the M-103 Supply FRV, in any seat; the FRVs' tires each show their own health and go clear when popped. Only you see it.": '用小型轮廓显示载具火炮相对车体的指向，并按血量着色（蓝到红）。适用于堡垒、漩涡、M-102 FRV 与 M-103 补给 FRV 的任意座位；FRV 的每个轮胎单独显示血量，爆胎后变透明。只有你能看到。',
    'SMARTER GUARD DOGS & SENTRIES': '更聪明的护卫犬与哨戒炮',
    "How your dogs and sentries choose what to shoot. Armor Intelligence: they leave alone armor they can't hurt, fire only short bursts at Heavy Devastators, and no sentry wastes ammo on dropships. Target Prioritization: your dog goes for the closest threat to you first; your sentries deal with enemies at their feet, Gunships and the armor that suits the gun first. Turn off to leave both to the game.": '你的护卫犬与哨戒炮如何选择射击目标。装甲识别：放过打不穿的装甲目标，对重型毁灭者只做短点射，哨戒炮不会把弹药浪费在运输舰上。目标优先：护卫犬优先攻击离你最近的威胁；哨戒炮优先处理脚下的敌人、炮艇以及适合其火力的装甲。关闭后两项都交还给游戏。',
    "Who your dog and your sentries never fire through: they hold fire while that helldiver is in their line of fire, don't swing their fire across them, mortars and the rocket sentry leave enemies next to them alone, and the Tesla Tower doesn't zap them or arc into them. Turn off at your own risk: they will fire through anyone. Everything else keeps working.": '你的护卫犬与哨戒炮绝不误伤的对象：当该潜兵位于射线上时它们会停火，不会把火力扫过对方，迫击炮与火箭哨戒炮会放过紧挨着对方的敌人，特斯拉塔也不会电到或电弧到对方。关闭后果自负：它们会朝任何人开火。其余功能不受影响。',
    "Laser out of the barrel of your guard dog and your sentries (not the mortars) toward their targets, shown only on your screen: green while they fire, flashing red when the safety stops a shot, flashing yellow when the dog's target goes out of sight. The Tesla Tower shows its reach as a yellow ring. Line: thin, hidden by walls. Glow: a soft beam that shows through walls.": '从护卫犬与哨戒炮（迫击炮除外）炮口射向目标的激光，仅你可见：开火时为绿色，被安全防护拦下时闪红，护卫犬丢失目标时闪黄。特斯拉塔以黄圈显示其作用范围。细线：纤细，会被墙挡住。辉光：柔和光束，可透过墙壁看到。',
    'Show objective tracker': '显示任务目标追踪',
    'Show only while map is open': '仅在打开地图时显示',
    'Display the tracker with the tactical map. The panel also appears in ESC for positioning and resizing.': '与战术地图一同显示追踪面板。该面板也会出现在 ESC 菜单中，供你调整位置与大小。',
    'Maximum visible targets': '最多显示目标数',
    'Show the nearest targets, sorted by distance. Panel height also limits how many rows fit.': '显示最近的目标，按距离排序。面板高度也会限制可容纳的行数。',
    'Maximum distance (meters)': '最大距离（米）',
    'Direct distance from your Helldiver to loaded objectives.': '从你的绝地潜兵到已加载目标的直线距离。',
    'Text and icon size (%)': '文字与图标大小（%）',
    'Set the text and icon size. Resizing the panel keeps this size and changes how many targets fit.': '设置文字与图标大小。调整面板尺寸会保留该字号，并改变可容纳的目标数量。',
    'Background opacity (%)': '背景不透明度（%）',
    'Icon and distance colors': '图标与距离颜色',
    'Objective colors': '目标配色',
    'Helldiver gold': '绝地潜兵金',
    'Ice white': '冰白',
    'Row spacing': '行间距',
    'Compact': '紧凑',
    'Comfortable': '宽松',
    'Support and retrieval objectives': '支援与回收类目标',
    'Radar stations, SEAF artillery, SAM sites, escape pod data and mutant larvae.': '雷达站、SEAF 火炮、防空导弹阵地、逃生舱数据与变异幼虫。',
    'Hostile nests and installations': '敌方巢穴与设施',
    'Research objective sites': '研究类目标地点',
    'Specimen pickups': '样本拾取物',
    'Show Automaton heads and mutated eggs with distance and direction.': '显示自动人形头颅与变异卵的距离和方向。',
    'Show item carrier': '显示物品携带者',
    'Show the carrier squad tag for Automaton heads, mutated eggs and mutant larvae.': '为自动人形头颅、变异卵与变异幼虫显示携带者的小队标签。',
    'Hide completed objectives': '隐藏已完成目标',
    'Hide objectives after the game reports completion. Completion affects only your HUD.': '当游戏报告目标完成后将其隐藏。该完成状态只影响你自己的 HUD。',
    'Hide destroyed sites': '隐藏已被摧毁的地点',
    'For sites without a readable objective state, hide the entry when every observed structure is dead or removed. Native objective state takes priority when available.': '对于无法读取任务状态的地点，当观察到的所有结构均已被摧毁或移除时隐藏该条目。若可读取原生任务状态，则以原生状态为准。',
    'Show panel aboard ship': '在飞船上也显示面板',
    'Detailed logging': '详细日志',
    'Write objective state details to the local log for troubleshooting.': '将任务状态详情写入本地日志，便于排查问题。',
    'HD2 Transmog': 'HD2 幻化',
    'Preview style': '预览风格',
    'Choose the lighting for generated previews. HD2 uses the approved rim lighting; Studio emphasizes front detail. Both styles stay cached. Items without an author choice use HD2.': '选择生成预览所用的光照。HD2 使用官方认可的轮廓光；Studio 更强调正面细节。两种风格的缓存都会保留。作者未指定时使用 HD2。',
    "Mod author's choice": '作者指定',
    'Force HD2': '强制 HD2',
    'Force Studio': '强制 Studio',
    'Armory 3D preview': '军械库 3D 预览',
    'Full render': '完整渲染',
    'Game default': '游戏默认',
    "Full render draws the large Armory model through the game's full pipeline, with hair and the lighting of the generated previews. It needs temporal anti-aliasing; without it, and with Game default, the game draws the model itself.": '完整渲染会通过游戏的完整渲染管线绘制大型军械库模型，包含头发以及生成预览所用的光照。它需要开启时间抗锯齿；若未开启，或者选择「游戏默认」，则由游戏自行绘制模型。',
    'Regenerate previews': '重新生成预览',
    'Keep cached images': '保留缓存图像',
    'Regenerate now': '立即重新生成',
    'Apply Regenerate now to refresh generated previews for the selected style. Requires a working renderer and an open Armory item list. Cached images remain available if rendering is unavailable.': '选择「立即重新生成」可用当前风格刷新已生成的预览。需要渲染器可用且军械库物品列表已打开。若渲染不可用，仍会保留缓存图像。',
    'SHOW / HIDE BADGE': '显示/隐藏徽章',
    'BADGE BIGGER': '放大徽章',
    'BADGE SMALLER': '缩小徽章',
    'MOVE BADGE UP': '上移徽章',
    'MOVE BADGE DOWN': '下移徽章',
    'MOVE BADGE LEFT': '左移徽章',
    'MOVE BADGE RIGHT': '右移徽章',
    'Select Next Transmog Piece': '选择下一件幻化部件',
    'Next Transmog Variant': '下一个幻化变体',
    'Previous Transmog Variant': '上一个幻化变体',
    'Refresh Transmog Look': '刷新幻化外观',
    'Custom Variant': '自订变体',
    'Shallow Water Diving': '浅水潜行',
    'Better Lobby Management': '大厅管理',
    'No variant selected': '未选择任何变体',
    '1  Resource ID': '1  资源 ID',
    '2  Icon material': '2  图标材质',
    '3  Texture binding': '3  贴图绑定',
    '4  Configured icon': '4  已配置图标',
    'Kick Test': '踢人测试',
    'Promote Notice': '提升通知',
    'Ship Station Hotkeys': '舰内站点快捷键',
}
