# -*- coding: utf-8 -*-
"""cn_strings.py —— 英文原文 -> 简体中文 词表（Mod Options Menu 选项文本 / 模组名 / 选项说明）。

合并自 cn_add / cn_desc / cn_fix / cn_mods / cn_mods2 / cn_new，共 875 条；
键必须与模组注册时传入的字符串逐字符一致。
"""

CN = {
    'All': '全部',
    'Default': '默认',
    'Off': '关',
    'On': '开',
    'On (default)': '开（默认）',
    'OFF': '关',
    'Show': '显示',
    'Hide': '隐藏',
    'Dim': '暗淡',
    'Red': '红色',
    'Green': '绿色',
    'Standard': '标准',
    'Mild': '轻微',
    'Stable': '稳定',
    'Planted': '沉稳',
    'Balanced': '均衡',
    'Combined': '组合',
    'Integrated': '一体化',
    'Rings': '圆环',
    'Simple': '简洁',
    'Faint': '微弱',
    'Full brightness': '全亮',
    'Line': '线状',
    'Glow': '光晕',
    'Gameplay': '游戏性',
    'Task Light': '作业灯',
    'Core': '核心',
    'Cells': '显示项目',
    'Squad': '小队',
    'Stratagems': '战略配备',
    'Textures': '贴图',
    'textures': '贴图',
    'Default.': '默认。',
    'Default. Stays visible, faded.': '默认。保持可见但变暗。',
    'Always fully visible.': '始终完全可见。',
    'Pick one colour.': '选择一种颜色。',
    'Both.': '两者都启用。',
    'made by Dekr0': '作者：Dekr0',
    'This is the default mod, no added music.': '默认版本，无附加音乐。',
    '1.9 m up.': '高度 1.9 米。',
    '2.2 m up.': '高度 2.2 米。',
    '2.5 m up: the widest view.': '高度 2.5 米：视野最广。',
    '6 degrees below to 30 above.': '下 6 度至上方 30 度。',
    '10 degrees below to 35 above.': '下 10 度至上方 35 度。',
    '15 degrees below to 45 above.': '下 15 度至上方 45 度。',
    'About 31 degrees a second.': '约每秒 31 度。',
    'About 44 degrees a second.': '约每秒 44 度。',
    '37.5 degrees a second.': '每秒 37.5 度。',
    '50 degrees a second.': '每秒 50 度。',
    '52.5 degrees a second.': '每秒 52.5 度。',
    '70 degrees a second.': '每秒 70 度。',
    'A quarter more grip.': '抓地力 +25%。',
    'A quarter more pulling power.': '牵引力 +25%。',
    'A quarter quicker.': '转向快 25%。',
    'Half again as quick.': '转向快 50%。',
    'Half again the grip.': '抓地力 +50%。',
    'Half again the pulling power.': '牵引力 +50%。',
    'Twice the pulling power.': '牵引力 ×2。',
    'Castle': 'Castle',
    'UA Camo': '内衬迷彩',
    'Under Armor Camo': '内衬迷彩',
    'Armor Camo': '护甲迷彩',
    'Camo on Armor': '护甲迷彩',
    'Black ODST': '黑色 ODST',
    'Black/greys with no camo': '黑灰色，无迷彩',
    'Replaces CPG-48 Snapper': '替换 CPG-48「工兵」',
    'DP8': 'DP8',
    'RS67': 'RS67',
    'A9': 'A9',
    'Replaces medium siege ready set': '替换中型攻坚套装',
    'Replaces medium stealth set': '替换中型潜行套装',
    'Replaces helljumper set': '替换「地狱伞兵」套装',
    'Required for all replacers': '所有替换外观共用，必需',
    'Ammo Box': '弹药箱',
    'Stim Box': '兴奋剂箱',
    'Grenade Box': '手雷箱',
    'Supply Pod': '补给舱',
    'Support Weapon Pod': '支援武器舱',
    'Icon and Glow': '图标 + 光晕',
    'Icon and Glow LARGER': '图标 + 光晕（更大）',
    'Icon and Glow LODs': '图标 + 光晕（含远距 LOD）',
    'Glow Only': '仅光晕',
    'No Glow': '无光晕',
    'Static Icon': '静态图标',
    'Larger Icon Appears When Far': '远距离时显示更大图标',
    "Doesn't Support LODs Large Icon Only": '不支持远距 LOD，仅显示大图标',
    'Sentry Turrets': '哨戒炮塔',
    'Guard Dog Drones': '护卫犬无人机',
    'Smarter Guard Dogs and Sentries': '更聪明的护卫犬与哨戒炮',
    'Guard Dogs': '护卫犬',
    'Sentries': '哨戒炮',
    'All sentries': '所有哨戒炮',
    'All but the Tesla Tower': '除特斯拉塔外的所有哨戒炮',
    'Every sentry, the Tesla Tower included.': '所有哨戒炮，包括特斯拉塔。',
    'Intelligence': '智能判断',
    'Armor Intelligence and Target Prioritization': '装甲判断 + 目标优先级',
    'Only Armor Intelligence': '仅装甲判断',
    'Only Target Prioritization': '仅目标优先级',
    'Safety': '安全保护',
    'You and your teammates': '你与队友',
    'Only you': '仅你',
    'Only your teammates': '仅队友',
    'Protects you and the other players.': '保护你和其他玩家。',
    'Targeting Laser': '瞄准激光',
    'Laser Brightness': '激光亮度',
    'Normal (100%)': '正常（100%）',
    'Dim (50%)': '暗淡（50%）',
    'Softer (75%)': '柔化（75%）',
    'Bright (150%)': '明亮（150%）',
    'Brightest (200%)': '最亮（200%）',
    'The laser as it has always been.': '与原版一致的激光。',
    'Aggro Counter': '仇恨计数',
    'Position': '位置',
    'Size': '尺寸',
    'Left of the compass': '罗盘左侧',
    'Right of the compass': '罗盘右侧',
    'Under the warning banners': '警告横幅下方',
    'Nearby only': '仅附近',
    'Without nearby': '不含附近',
    'Searching + On you': '搜索中 + 锁定你',
    'Searching, on you and on teammates.': '搜索中、锁定你、锁定队友。',
    'Only the enemies that are after you.': '只统计正在追击你的敌人。',
    'When nothing is counted': '计数全为零时',
    'The counter badge. Required.': '计数器徽章。必需。',
    'Default mode': '默认模式',
    'The headlamp controller. Required.': '头灯控制器。必需。',
    'Gameplay-first flood, about 35-40 m.': '偏游戏性的泛光照明，约 35-40 米。',
    'HD2 Transmog Foundation': 'HD2 Transmog 基础组件',
    'Independent armor stats (default)': '独立护甲属性（默认）',
    'Disable armor stat selection': '禁用护甲属性选择',
    'Choose look, base stats, then passive.': '依次选择外观、基础属性、被动。',
    'Helmet and cape variants': '头盔与披风变体',
    'Disable helmet and cape variants.': '禁用头盔与披风变体。',
    'Armor thumbnail passive icons': '护甲缩略图被动图标',
    'Show passive badges on armor thumbnails.': '在护甲缩略图上显示被动徽章。',
    'Tank Power': '坦克动力',
    'Tank Grip': '坦克抓地',
    'Tank Steering': '坦克转向',
    'Tank Suspension': '坦克悬挂',
    'Strong (x1.25)': '强（×1.25）',
    'Stronger (x1.5)': '更强（×1.5）',
    'Strongest (x2)': '最强（×2）',
    'Moderate (x1.25)': '中等（×1.25）',
    'Strong (x1.5)': '强（×1.5）',
    'Maximum (x2)': '最大（×2）',
    'Responsive (x1.25)': '灵敏（×1.25）',
    'Quick (x1.5)': '快速（×1.5）',
    'Sharp (x2)': '锐利（×2）',
    'Quick (x1.25)': '快速（×1.25）',
    'Fast (x1.5)': '迅捷（×1.5）',
    'Very fast (x2)': '极快（×2）',
    'Wide (-6..+30 deg)': '宽（-6..+30 度）',
    'Wider (-10..+35 deg)': '更宽（-10..+35 度）',
    'Widest (-15..+45 deg)': '最宽（-15..+45 度）',
    'Tank MBT Turrets': '坦克炮塔全向旋转',
    'Tank Turret Traverse': '炮塔回旋速度',
    'Tank Turret Elevation': '炮塔俯仰速度',
    'Tank Turret Aim Range': '炮塔俯仰范围',
    'Tank Autoloader': '坦克自动装填',
    'Gunner Drive': '炮手位驾驶',
    'Tanks and FRV': '坦克与 FRV',
    'Tanks': '坦克',
    'Tank Gunner Camera': '坦克炮手视角',
    'Close (1 m behind)': '近（后方 1 米）',
    'Far (3.5 m behind)': '远（后方 3.5 米）',
    'Farther (5.4 m behind)': '更远（后方 5.4 米）',
    'Farthest (7.4 m behind)': '最远（后方 7.4 米）',
    'Both the tanks and the M-102 FRV.': '坦克和 M-102 FRV 都启用。',
    'The M-102 FRV, from its gunner seat.': 'M-102 FRV，可在炮手座驾驶。',
    'FRV Stability': 'FRV 稳定性',
    'Vehicle Indicator': '载具指示器',
    'Minimap Settings (Map Marker)': '小地图设置（地图标记）',
    'Minimap Settings (Enemy Blips)': '小地图设置（敌人光点）',
    'Minimap Settings (View Cones)': '小地图设置（视野扇形）',
    'Compass Settings (Super Destroyer Indicator)': '罗盘设置（超级驱逐舰指示）',
    'DIAMOND (GAPPED, OUTLINED)': '菱形（间断、描边）',
    'DIAMOND (GAPPED)': '菱形（间断）',
    'DIAMOND (THICK, GAPPED, OUTLINED)': '菱形（粗、间断、描边）',
    'DIAMOND (THICK, GAPPED)': '菱形（粗、间断）',
    'DIAMOND (THICK, OUTLINED)': '菱形（粗、描边）',
    'DIAMOND (THICK)': '菱形（粗）',
    'DIAMOND (THICK, HOLLOWED, OUTLINED)': '菱形（粗、空心、描边）',
    'DIAMOND (THICK, HOLLOWED)': '菱形（粗、空心）',
    'DIAMOND (THICK, HOLLOWED, GAPPED, OUTLINED)': '菱形（粗、空心、间断、描边）',
    'DIAMOND (THICK, HOLLOWED, GAPPED)': '菱形（粗、空心、间断）',
    'HEXAGON (OUTLINED)': '六边形（描边）',
    'HEXAGON': '六边形',
    'RING (OUTLINED)': '圆环（描边）',
    'RING': '圆环',
    'POINTERS (OUTLINED)': '指针（描边）',
    'POINTERS': '指针',
    'ARROWS (OUTLINED)': '箭头（描边）',
    'ARROWS': '箭头',
    'CROSS (OUTLINED)': '十字（描边）',
    'CROSS': '十字',
    'CIRCLE (SMALL)': '圆形（小）',
    'SKULL (SMALL)': '骷髅（小）',
    'SKULL': '骷髅',
    'SUPER DESTROYER': '超级驱逐舰',
    'OUTLINED': '描边',
    'VANILLA': '原版',
    'HUD layout': 'HUD 布局',
    'Show when idle': '待机时显示',
    'Game crosshair': '游戏自带准星',
    'HD2 HUD+': 'HD2 抬头显示+',
    'All Mechs': '全部机甲',
    'No Muzzle Flash Smoke': '枪口无烟',
    'No Smoke Heat or Sparks - LAS 16 Sickle': '无烟、无热浪、无火花 - LAS-16 镰刀',
    'No Smoke Heat or Sparks - LAS 17 DE Sickle - Talon': '无烟、无热浪、无火花 - LAS-17 DE 镰刀 - 爪',
    'Autocannon Sentry': '机炮哨戒炮',
    'Gatling Sentry': '加特林哨戒炮',
    'Machinegun Sentry': '机枪哨戒炮',
    'Mortar Sentry': '迫击炮哨戒炮',
    'Rocket Sentry': '火箭哨戒炮',
    'Flak36': 'Flak36',
    'Flak36 (no pings)': 'Flak36（无提示音）',
    'Flak36 (quieter pings)': 'Flak36（提示音更轻）',
    'Flakm42': 'Flakm42',
    'Flakm42 (no pings)': 'Flakm42（无提示音）',
    'Flakm42 (quieter pings)': 'Flakm42（提示音更轻）',
    'KWK36': 'KWK36',
    'KWK36 (no pings)': 'KWK36（无提示音）',
    'KWK36 (quieter pings)': 'KWK36（提示音更轻）',
    '40mm bofors': '40mm 博福斯',
    'QF 2 Pounder': 'QF 2 磅炮',
    'Gau-19': 'Gau-19',
    'Gau-12': 'Gau-12',
    'M197': 'M197',
    'M61': 'M61',
    'C-RAM': 'C-RAM',
    'M134': 'M134',
    'BAR': 'BAR',
    'MG34': 'MG34',
    'MG42': 'MG42',
    'M240': 'M240',
    'MG3': 'MG3',
    'PKM': 'PKM',
    'BF1 Mortar': 'BF1 迫击炮',
    'Squad 81mm': '小队 81mm 迫击炮',
    'Malyutka': 'Malyutka',
    'Hydra': 'Hydra',
    'Menacing Recoilless Rifle': '威压 无后坐力步枪',
    'Menacing Laser Cannon': '威压 激光炮',
    'Menacing Quasar Cannon': '威压 类星体炮',
    'Menacing Autocannon': '威压 机炮',
    'Menacing Railgun': '威压 磁轨炮',
    'Menacing Epoch': '威压 Epoch',
    'Menacing Flamethrower': '威压 火焰喷射器',
    'Menacing Spear': '威压 长矛',
    'Menacing Exosuits': '威压 外骨骼',
    'Menacing HMG': '威压 重机枪',
    'Menacing Maxigun': '威压 转轮机枪',
    'Quiet Ping': '轻提示音',
    'Loud Ping': '明显提示音',
    'UnSafe Mode': '不安全模式',
    'Safe Mode': '安全模式',
    'Standard Horn': '标准号角',
    'MVM Horn': 'MvM 号角',
    '40K Horn': '40K 号角',
    'Meet The Medic': 'Meet The Medic',
    'Changes firing, idle, and repel sounds.': '替换开火、待机与驱离音效。',
    'Badge size. Fine-tune in game with Ctrl+Shift+= / -.': '徽章尺寸。游戏内可用 Ctrl+Shift+= / - 微调。',
    'Beside the compass, on its right (less room: up to about 150%).': '罗盘右侧（空间较小：最大约 150%）。',
    'Default. Beside the compass, on its left (room up to about 185%).': '默认。罗盘左侧（空间较大：最大约 185%）。',
    'Centred below the compass and the game warning banners.': '居中显示在罗盘与游戏警告横幅下方。',
    'Shrinks to fit beside the compass (about 185% on the left).': '会自动缩小以贴合罗盘（左侧约 185%）。',
    'Just the radar number: every live enemy within 60m of you.': '只显示雷达数字：你周围 60 米内的所有存活敌人。',
    'Default. Nearby, searching, on you and on teammates.': '默认。附近、搜索中、锁定你、锁定队友。',
    'Only appears when an enemy targets or searches for you or a teammate.': '仅当有敌人锁定或搜索你/队友时才出现。',
    'What the badge does while every count is 0.': '所有计数为 0 时徽章的表现。',
    'Where the badge sits. It grows away from the compass when enlarged.': '徽章所在位置。放大时会朝背离罗盘的方向扩展。',
    'Which numbers the badge shows. Other combinations: cells in the settings file.': '徽章显示哪些数字。其它组合：见设置文件中的 cells。',
    'Beside the compass: enemies near you, searching for you, targeting you, and targeting your teammates. Requires Bingus Shared Loader v18 or newer.': '在罗盘旁显示：附近的敌人、正在搜索你的敌人、锁定你的敌人，以及锁定队友的敌人。需要 Bingus Shared Loader v18 或更新版本。',
    'The guard dog and sentry improvements (safety, closest threat first, no shooting the dead, no shooting into cover, Guard Dog range, Rover fire spreading; sentries that do not fire through you or swing their fire across you, stop firing into walls, deal with enemies at their feet first, a Laser Sentry that sets enemies alight and moves on like the Rover and cools down before it burns out, and a Tesla Tower that leaves helldivers and enemies next to them alone). Keep this on.': '护卫犬与哨戒炮的整体改进（安全保护、优先最近的威胁、不射击尸体、不朝掩体开火、护卫犬射程、漫游者火焰蔓延；哨戒炮不会穿过你开火或把弹道扫过你、不会对着墙射击、优先处理脚下的敌人；激光哨戒炮能点燃敌人并像漫游者那样转移目标、过热前会先冷却；特斯拉塔不再电击绝地潜兵及其旁边的敌人）。请保持开启。',
    'The mod handles your guard dog (Guard Dog, Rover, K-9). Turn off to leave your dog to the game; your sentries and the rest of the mod keep working.': '由本模组接管你的护卫犬（护卫犬、漫游者、K-9）。关闭则护卫犬交回游戏处理，哨戒炮与本模组其它功能照常工作。',
    'The mod handles your sentries (Machine Gun, Gatling, Autocannon, Rocket, Laser, Flame, Mortar, EMS Mortar and the Tesla Tower), plus the guns on armed resupply pods and the Supply FRV. Turn off to leave your sentries to the game; your guard dog and the rest of the mod keep working.': '由本模组接管你的哨戒炮（机枪、加特林、机炮、火箭、激光、火焰、迫击炮、电磁迫击炮与特斯拉塔），以及武装补给舱和补给 FRV 上的机枪。关闭则哨戒炮交回游戏处理，护卫犬与本模组其它功能照常工作。',
    'Every sentry except the Tesla Tower, which is left to the game.': '除特斯拉塔外的所有哨戒炮（特斯拉塔交回游戏处理）。',
    'How your dogs and sentries choose what to shoot. Armor Intelligence: they leave alone armor they cannot get through (Hulks, Chargers, Tanks and similar; the Rover also Scout Striders; the Laser Sentry only what is above Heavy), fire only short bursts at Heavy Devastators, and no sentry wastes ammo on dropships (only the Rocket and Autocannon sentries shoot enemies still aboard one). Target Prioritization: your dog goes for the closest threat to you first; your sentries deal with enemies at their feet first, go for Gunships and Stingrays first (the Rocket Sentry only while one hovers), then the armor that suits the gun (Heavy for the Rocket and Autocannon, lighter for the Machine Gun, Gatling and Laser; the closest first for the Flame Sentry). Turn off to leave both to the game. Everything else keeps working.': '决定护卫犬与哨戒炮如何选择目标。装甲判断：跳过打不穿的装甲（浩克、冲锋虫、坦克等；漫游者还会跳过侦察追猎者；激光哨戒炮只打重型以上），对重型破坏者只点射，且没有哨戒炮会把弹药浪费在运输艇上（只有火箭与机炮哨戒炮会射击仍在艇上的敌人）。目标优先级：护卫犬优先攻击离你最近的威胁；哨戒炮优先处理脚下的敌人，其次优先炮艇与黄貂鱼（火箭哨戒炮只在悬停时），再按武器特性选择装甲（火箭与机炮打重型、机枪/加特林/激光打轻型；火焰哨戒炮优先最近）。关闭则两者都交回游戏，其余功能照常。',
    'Skip armor they cannot hurt and dropships; the game decides the order.': '跳过打不动的装甲和运输艇；攻击顺序由游戏决定。',
    'The right target first; they may shoot armor they cannot hurt.': '优先攻击正确的目标；可能对打不动的装甲开火。',
    'Who your dog and your sentries never fire through: they hold fire while that helldiver is in their line of fire, do not swing their fire across them, mortars and the rocket sentry leave enemies next to them alone, and the Tesla Tower does not zap them or arc into them. Turn off at your own risk: they will fire through anyone. Everything else keeps working.': '决定护卫犬与哨戒炮绝不穿过谁开火：当该绝地潜兵处于弹道上时停火、不把弹道扫过他们、迫击炮与火箭哨戒炮不攻击其身边的敌人、特斯拉塔不电击也不对其电弧。关闭需自行承担风险：它们会穿过任何人开火。其余功能照常。',
    'Protects the other players; they may fire through you.': '保护其他玩家；可能穿过你开火。',
    'Protects you; they may fire through other players.': '保护你；可能穿过其他玩家开火。',
    'Laser out of the barrel of your guard dog and your sentries (not the mortars) toward their targets, shown only on your screen: green while they fire, flashing red when the safety stops a shot (and a red ring around the rocket sentry while an enemy is too close for it to fire), flashing yellow when the dog target goes out of sight (cover or smoke), off while the dog reloads. The Tesla Tower shows its reach as a yellow ring instead. Turn off to hide it.': '从护卫犬与哨戒炮（迫击炮除外）枪口射向目标的激光，只在你屏幕上显示：开火时为绿色，安全保护拦下射击时闪红（敌人离火箭哨戒炮太近时它会显示红圈），护卫犬目标被掩体或烟雾遮挡时闪黄，装填时熄灭。特斯拉塔改以黄色圆环显示作用范围。关闭即隐藏。',
    'A thin, plain line with a small cross where it hits. Simple to look at, but walls and objects hide it.': '细直线，命中处有小十字。观感简洁，但会被墙壁和物体遮挡。',
    'A soft glowing beam with a bright spot on the target. It looks much better than the line, but it shows through walls and objects (the game draws it on top of the world).': '柔和光晕光束，命中点亮起光斑。比细线好看得多，但会穿透墙壁与物体（游戏把它绘制在世界之上）。',
    'How bright the targeting laser is: its beams and rings, line or glow.': '瞄准激光的亮度：包括光束与圆环、线状或光晕。',
    'The laser at 50% of its normal brightness.': '亮度为正常值 50% 的激光。',
    'The laser at 75% of its normal brightness.': '亮度为正常值 75% 的激光。',
    'The laser at 150% of its normal brightness.': '亮度为正常值 150% 的激光。',
    'The laser at 200% of its normal brightness.': '亮度为正常值 200% 的激光。',
    'Short-range helmet task light, about 20-25 m.': '近距离头盔作业灯，约 20-25 米。',
    'Initial mode; the mode key still switches it.': '初始模式；模式键仍可切换。',
    'Customise the appearance of the map marker.': '自定义地图标记的外观。',
    'Customise the appearance of the enemy blips (the solid red circles on the map which show enemy unit positions).': '自定义敌人光点的外观（地图上表示敌军位置的红色实心圆）。',
    'Customise the appearance of Helldiver view cones on the minimap.': '自定义小地图上绝地潜兵视野扇形的外观。',
    'Customise the appearance of the Super Destroyer compass indicator.\n(NOTE: This is only enabled in megacity missions.)': '自定义超级驱逐舰罗盘指示器的外观。\n（注意：仅在巨型城市任务中启用。）',
    'Body-armor creation process. Helmet/cape and icon settings are independent.': '护甲创建流程。头盔/披风与图标设置相互独立。',
    'Choose look and passive; the look supplies base stats.': '选择外观与被动；基础属性由外观决定。',
    'Shared variant creator for detected helmet/cape passives. On by default.': '为识别到的头盔/披风被动提供共享的变体创建器。默认开启。',
    'Use the same + creator for helmets and capes with detected gameplay changes.': '对检测到玩法变化的头盔与披风，使用同一个「+」创建器。',
    'Show or hide passive badges on armor thumbnails. On by default.': '在护甲缩略图上显示或隐藏被动徽章。默认开启。',
    'Hide thumbnail badges; passive-selection and detail-panel icons stay visible.': '隐藏缩略图上的徽章；被动选择界面与详情面板的图标仍然显示。',
    'More pulling power for the Bastion and Maelstrom: quicker off the line and up slopes. Top speed is unchanged.': '提升堡垒与漩涡的牵引力：起步与爬坡更快。最高速度不变。',
    'More track grip for the Bastion and Maelstrom: less sliding on slopes and in turns.': '提升堡垒与漩涡的履带抓地力：在斜坡与转弯时更少打滑。',
    'Quicker steering for the Bastion and Maelstrom: they start and stop turning sooner.': '提升堡垒与漩涡的转向响应：起转与停转都更快。',
    'Road wheels that work like a tank: the game tanks rest on their bump stops, so the wheels cannot move. Here each wheel rests part-way down a longer travel and follows the ground, keeping its track down, well damped; the hull is no longer thrown sideways when one track unloads. The tanks ride a little higher than in the game.': '像真实坦克那样工作的负重轮：原版坦克压在缓冲块上，轮子无法活动。本模组让每个轮子在更长的行程中半悬并贴合地面，履带始终压地、阻尼充分；单侧履带卸载时车体不再被甩向一侧。车体会比原版略高一点。',
    'Half a metre of wheel travel, each wheel resting half-way: soaks up rough ground; the hull resists being rolled and the grip is shared between the tracks.': '轮行程半米、每个轮子停在中间位置：能吸收崎岖地面；车体不易被翻覆，抓地力由两侧履带共同承担。',
    'Stiffer, more damped wheels with a little less travel; the hull is very hard to roll and the tracks share almost all the grip.': '轮子更硬、阻尼更强、行程略短；车体极难翻覆，几乎全部抓地力由履带承担。',
    'The Bastion and Maelstrom turrets turn all the way round like a main battle tank. The Maelstrom missile pods and smoke launchers turn with it. Only you see the new turrets, and their armor always looks undamaged.': '堡垒与漩涡的炮塔可像主战坦克那样 360 度旋转。漩涡的导弹发射巢与烟雾发射器随之转动。新炮塔只有你自己能看到，且其装甲始终显示为完好。',
    'How fast the Bastion and Maelstrom turrets turn (the game: 25 degrees a second). Works with or without MBT Turrets.': '堡垒与漩涡炮塔的转速（原版：每秒 25 度）。无论是否开启「炮塔全向旋转」都有效。',
    'How fast the Bastion and Maelstrom guns move up and down (the game: 35 degrees a second).': '堡垒与漩涡火炮的俯仰速度（原版：每秒 35 度）。',
    'How far down and up the Bastion and Maelstrom guns aim (the game: 3 below to 25 above).': '堡垒与漩涡火炮的俯仰范围（原版：下 3 度至上 25 度）。',
    'The Bastion and Maelstrom main gun reloads by itself when it runs dry, at the normal reload speed (perks count). You can still reload by hand.': '堡垒与漩涡的主炮打空后会自动装填，速度为正常装填速度（受相关加成影响）。仍可手动装填。',
    'Drive from the gunner seat when the driver seat is empty: your movement keys drive, the gun works as normal, and a driver panel shows gear, rpm, speed and fuel. F sounds the horn; in the Maelstrom, Mouse 3 pops smoke. On a controller the left stick drives, its click sounds the horn and the right stick click pops smoke. A teammate who takes the wheel drives as normal, and getting out while it rolls brakes it to a stop. With the Mod Bindings Menu you can set your own keys (controls, tab MODS). Pick which vehicles.': '驾驶位空置时可在炮手座驾驶：移动键控制行驶，武器照常工作，并显示档位、转速、速度与燃料面板。按 F 鸣笛；漩涡上鼠标中键释放烟雾。手柄用左摇杆驾驶、按下鸣笛、右摇杆按下放烟雾。队友接方向盘后按正常方式驾驶；行驶中下车会自动刹停。配合「模组按键菜单」可自定义按键（控制设置里的 MODS 分页）。可选择适用于哪些载具。',
    'Puts the Bastion and Maelstrom gunner camera lower and further back so you see more around the tank. It stays behind the turret as it turns.': '把堡垒与漩涡的炮手视角放得更低更靠后，便于观察坦克周围。视角会始终跟随炮塔后方。',
    'The game distance, 1.4 m up (the game: 2 m).': '与原版一致的距离，高度 1.4 米（原版为 2 米）。',
    'Keeps the M-102, M-103 and M-104 FRVs on their wheels over rough ground, jumps and hard turns: a firmer front, longer suspension travel, a lower center of mass, more grip and weight, and a little more ground clearance. Engine and steering stay the game own.': '让 M-102、M-103、M-104 FRV 在崎岖地面、跳跃与急转弯时保持四轮着地：前悬更硬、悬挂行程更长、重心更低、抓地与重量更高，离地间隙略增。引擎与转向保持原版。',
    'Half the change: still lively, far less likely to roll.': '改动一半：依然灵活，但翻车概率大幅降低。',
    'Stays upright over rough ground, jumps and hard turns; a quarter heavier.': '在崎岖地面、跳跃与急转弯时保持直立；重量增加四分之一。',
    'Lower, grippier, stiffer and 40% heavier, and the chassis resists rolling: very hard to tip, slower to turn.': '更低、更抓地、更硬且重量 +40%，车架抗翻覆：极难翻车，但转向变慢。',
    'A small outline of your vehicle shows where the gun points compared to the hull, colored by health (blue to red). Works in the Bastion, the Maelstrom, the M-102 FRV and the M-103 Supply FRV, in any seat; the FRVs tires each show their own health and go clear when popped. Only you see it.': '屏幕上的载具小轮廓显示炮口相对车体的朝向，颜色随耐久变化（蓝到红）。堡垒、漩涡、M-102 FRV、M-103 补给 FRV 的任意座位均可用；FRV 的每个轮胎单独显示耐久，爆胎后变透明。只有你自己能看到。',
    'Required for the HUD to work. Keep this enabled and use the options below to choose what is displayed.': 'HUD 运行所必需。请保持启用，并在下面选择要显示的内容。',
    'Enabled by default. Choose one: Integrated / Rings / Simple.': '默认开启。三选一：一体化 / 圆环 / 简洁。',
    'Under the crosshair: a charge, reload, heat or rounds arc, ammo, reserve ammo, health/stamina bars, stims, throwables, backpack. Best with game HUD on Map only.': '准星下方：充能/装填/热量/弹数弧线、弹药、备弹、生命与耐力条、兴奋剂、投掷物、背包。建议把游戏 HUD 设为「仅地图」。',
    'A ring by the crosshair shows charge, reload, heat or rounds; another shows a backpack own resource. Plus ammo, reserve ammo and weapon setting icons.': '准星旁的一个圆环显示充能、装填、热量或弹数；另一个圆环显示背包资源。另含弹药、备弹与武器状态图标。',
    'Weapon setting icons only - fire mode, function, scope zoom - beside the game weapon panel. Fixed brightness, and they hide when that panel hides.': '只显示武器状态图标（射击模式、功能、倍镜）在游戏武器面板旁。亮度固定，随该面板一同隐藏。',
    'Enabled by default. Choose one: Faint / Full brightness.': '默认开启。二选一：微弱 / 全亮。',
    'Dims the crosshair HUD to 30% brightness when idle. Does not affect Simple or squad icons.': '待机时把准星 HUD 亮度降到 30%。不影响「简洁」模式与小队图标。',
    'Keeps the crosshair HUD at full brightness when idle. Does not affect Simple or squad icons.': '待机时保持准星 HUD 全亮。不影响「简洁」模式与小队图标。',
    'Each squad row shows that player booster, yours last - a skull while that player is dead, or what they just pinged. Stratagems they call stack along the row. All hide with it.': '小队每行显示该玩家的增益（你自己在最后）——该玩家阵亡时显示骷髅，或显示他刚标记的内容。他们呼叫的战略配备会沿该行堆叠。整块显示可一并隐藏。',
    'The stratagems you chose, on a row at the bottom center: each drains on the way in, fills back as it cools, shows uses left while ready, carries a soft tint of its in-game colour while ready that turns full and enlarges while its beacon is out, and goes grey when the game blocks it.': '你选择的战略配备，排列在屏幕底部中央：呼叫时逐渐消耗、冷却时回填、就绪时显示剩余次数；就绪时带有其游戏内颜色的淡色标记，信标投放期间变为实色并放大；被游戏禁用时变灰。',
    'Lets the game draw its own crosshair for the Anti-Materiel Rifle in third person and the Maxigun in first person. It follows the game crosshair setting.': '让游戏为第三人称的反器材步枪与第一人称的转轮机枪绘制自带准星。跟随游戏的准星设置。',
    'Removes the smoke from firing a weapon while keeping the muzzle flash.': '移除开火时的硝烟，同时保留枪口火光。',
    'Enhances the sounds of the Sentries': '强化哨戒炮的音效',
    'Changes firing, shell eject, and shell impact sounds.': '替换开火、抛壳与炮弹命中音效。',
    'Changes charge-up, firing, and overheat alarm sounds.': '替换充能、开火与过热警报音效。',
    'Changes charge-up, firing, cooldown, and ready-state sounds.': '替换充能、开火、冷却与就绪状态音效。',
    'Changes firing, reload (with ping), and gun open/close sounds.': '替换开火、装填（含提示音）与炮闩开合音效。',
    'A subtle, low-volume ping heard while shooting.': '射击时能听到的轻微、低音量提示音。',
    'A distinct, much louder ping heard while shooting.': '射击时能听到的明显、音量更大的提示音。',
    'Changes firing, reload, and charge-up sounds, including safety mode alerts.': '替换开火、装填与充能音效，并包含安全模式提示音。',
    'Includes an alarm to warn you when you are about to explode.': '包含即将过载爆炸时的警报音。',
    'Includes a sound cue for reaching maximum safe charge.': '包含达到最大安全充能时的提示音。',
    'Combines Unsafe and Safe sounds. Note: Slightly less immersive due to overlapping cues.': '同时包含「不安全」与「安全」音效。注意：提示音重叠，代入感略降。',
    'Changes firing, charge-up, and reload sounds; adds a warning as you near max charge.': '替换开火、充能与装填音效；接近最大充能时增加警告音。',
    'Changes firing, lock-on, and target-locked sounds.': '替换开火、锁定与锁定完成音效。',
    'Changes enter/exit, movement, engine, and stomp sounds for Patriot and Emancipator.': '替换爱国者与解放者的进出舱、移动、引擎与踏步音效。',
    'The default menacing horn sound for the Exosuit.': '外骨骼默认的威压号角声。',
    'The iconic mechanical roar of the MvM Tank from Team Fortress 2.': '《军团要塞 2》中 MvM 坦克标志性的机械咆哮。',
    'The iconic Warlord Titan Warhorn from the 40K universe.': '40K 世界观中战将泰坦标志性的战争号角。',
    'Doctor! Are you sure this will work? Ha ha ha, I have no idea!': '医生！你确定这能行？哈哈哈，我完全不知道！',
    'Changes firing, wind-up/down and spin-loop audio.': '替换开火、加速/减速与旋转循环音效。',
    'Changes the firing sound (more updates planned).': '替换开火音效（后续还会继续更新）。',
    'ARSENAL: place this loader LAST (bottom of the list) with default priority, or FIRST if first-mod priority is enabled. Required by Armory Preview Cache, Know Your Constellation, Controllable Hover Pack, Vehicle Stability, Enemy Collision Synchronized, Vanilla Plus Megapack or the separate Better Stratagem Bounce, Hellpod Steering Unlocked, Reinforcement Beacons Fixed, Consistent Vaulting, Shallow Water Diving and Sentry Aim Retention mods. Import this ZIP through Arsenal or HD2MM, enable it alongside the megapack or your chosen mods, then Deploy. Also supports HUD Ballistic Trajectory Overlay v2.': 'Arsenal 用法：把本加载器放在列表最后（默认优先级），或在使用「首个模组优先」时放在最前。以下模组需要它：军械库预览缓存、敌情预测、悬浮背包可控下降、载具稳定性、敌人碰撞同步修正、Vanilla Plus 合集，或单独的「战备球弹射优化」「地狱舱转向解锁」「增援信标修正」「翻越判定稳定化」「浅水区飞扑」「哨戒炮瞄准保持」。请用 Arsenal 或 HD2MM 导入本 ZIP，与合集或你选的模组一起启用，然后 Deploy。同时支持「HUD 弹道轨迹叠加 v2」。',
    'Builds 25327279, 25480438 only. GL-52 owner exclusion; damage and range unchanged. Unknown game modules stop safely. Requires Bingus Shared Loader v15+ / API 1 and discovery.': '仅支持 25327279、25480438 版本。GL-52 排除发射者自身；伤害与射程不变。遇到未知游戏模块会安全停止。需要 Bingus Shared Loader v15+ / API 1 与 discovery。',
    '(v3.0.6) Redesigned, clear and precise map markers.': '（v3.0.6）重新设计，地图标记更清晰精准。',
    "A ring by the crosshair shows charge, reload, heat or rounds; another shows a backpack's own resource. Plus ammo, reserve ammo and weapon setting icons.": '准星旁的一个圆环显示充能、装填、热量或弹数；另一个显示背包自身资源。另含弹药、备弹与武器状态图标。',
    'All-in-one file; choose which weapon sounds you want to use.': '整合包：自行选择要使用哪些武器音效。',
    'Ammo, reload, charge, backpack, health and stratagems - read them without looking away from your target.': '弹药、装填、充能、背包、生命与战略配备——不必移开视线就能看清。',
    'Bastion, Maelstrom and FRV upgrades, each its own option: tank power, grip, steering and suspension; 360-degree MBT turrets with traverse, elevation and aim range; an autoloader; driving from the gunner seat; gunner camera distance; FRV stability; and a vehicle indicator. With the Mod Options Menu, the options can be changed in game. Requires Bingus Shared Loader.': '堡垒、漩涡与 FRV 的升级，每项独立可选：坦克动力、抓地、转向与悬挂；360 度主战坦克炮塔（含回旋、俯仰与俯仰范围）；自动装填；炮手座驾驶；炮手视角距离；FRV 稳定性；载具指示器。配合「模组选项菜单」可在游戏内调整。需要 Bingus Shared Loader。',
    'Beside the compass: enemies near you, searching for you, targeting you, and targeting your teammates. Requires Bingus Shared Loader v15 or newer / API 1.': '在罗盘旁显示：附近的敌人、正在搜索你的敌人、锁定你的敌人，以及锁定队友的敌人。需要 Bingus Shared Loader v15 或更新版本 / API 1。',
    "Customise the appearance of the enemy 'blips' (the solid red circles on the map which show enemy unit positions).": '自定义敌人光点的外观（地图上表示敌军位置的红色实心圆）。',
    "Each squad row shows that player's booster, yours last - a skull while that player is dead, or what they just pinged. Stratagems they call stack along the row. All hide with it.": '小队每行显示该玩家的增益（你自己在最后）——该玩家阵亡时显示骷髅，或显示他刚标记的内容。他们呼叫的战略配备会沿该行堆叠。整块显示可一并隐藏。',
    "How your dogs and sentries choose what to shoot. Armor Intelligence: they leave alone armor they can't get through (Hulks, Chargers, Tanks and similar; the Rover also Scout Striders; the Laser Sentry only what is above Heavy), fire only short bursts at Heavy Devastators, and no sentry wastes ammo on dropships (only the Rocket and Autocannon sentries shoot enemies still aboard one). Target Prioritization: your dog goes for the closest threat to you first; your sentries deal with enemies at their feet first, go for Gunships and Stingrays first (the Rocket Sentry only while one hovers), then the armor that suits the gun (Heavy for the Rocket and Autocannon, lighter for the Machine Gun, Gatling and Laser; the closest first for the Flame Sentry). Turn off to leave both to the game. Everything else keeps working.": '决定护卫犬与哨戒炮如何选择目标。装甲判断：跳过打不穿的装甲（浩克、冲锋虫、坦克等；漫游者还会跳过侦察追猎者；激光哨戒炮只打重型以上），对重型破坏者只点射，且没有哨戒炮会把弹药浪费在运输艇上（只有火箭与机炮哨戒炮会射击仍在艇上的敌人）。目标优先级：护卫犬优先攻击离你最近的威胁；哨戒炮优先处理脚下的敌人，其次优先炮艇与黄貂鱼（火箭哨戒炮只在悬停时），再按武器特性选择装甲（火箭与机炮打重型、机枪/加特林/激光打轻型；火焰哨戒炮优先最近）。关闭则两者都交回游戏，其余功能照常。',
    "Keeps the M-102, M-103 and M-104 FRVs on their wheels over rough ground, jumps and hard turns: a firmer front, longer suspension travel, a lower center of mass, more grip and weight, and a little more ground clearance. Engine and steering stay the game's own.": '让 M-102、M-103、M-104 FRV 在崎岖地面、跳跃与急转弯时保持四轮着地：前悬更硬、悬挂行程更长、重心更低、抓地与重量更高，离地间隙略增。引擎与转向保持原版。',
    "Laser out of the barrel of your guard dog and your sentries (not the mortars) toward their targets, shown only on your screen: green while they fire, flashing red when the safety stops a shot (and a red ring around the rocket sentry while an enemy is too close for it to fire), flashing yellow when the dog's target goes out of sight (cover or smoke), off while the dog reloads. The Tesla Tower shows its reach as a yellow ring instead. Turn off to hide it.": '从护卫犬与哨戒炮（迫击炮除外）枪口射向目标的激光，只在你屏幕上显示：开火时为绿色，安全保护拦下射击时闪红（敌人离火箭哨戒炮太近时它会显示红圈），护卫犬目标被掩体或烟雾遮挡时闪黄，装填时熄灭。特斯拉塔改以黄色圆环显示作用范围。关闭即隐藏。',
    "Lets the game draw its own crosshair for the Anti-Materiel Rifle in third person and the Maxigun in first person. It follows the game's crosshair setting.": '让游戏为第三人称的反器材步枪与第一人称的转轮机枪绘制自带准星。跟随游戏的准星设置。',
    'Owned armor, helmet and cape variants with independent appearance, stats and exact passives. Requires Bingus Shared Loader v15 or newer (API 1). Native stat/perk previews and one-button equipment in the Armor list. Create saves locally without equipping the armor.': '已拥有的护甲、头盔与披风变体，外观、属性与被动完全独立。需要 Bingus Shared Loader v15 或更新版本（API 1）。护甲列表内提供原生属性/被动预览与一键装备。可在不装备护甲的情况下本地创建存档。',
    'Recplaces all mechs with the concept mech': '把所有机甲替换为概念机甲',
    'Red or green laser sights on the six sentry turrets and the five Guard Dog drones, so you can see where they are aiming.': '为六种哨戒炮与五种护卫犬无人机加上红色或绿色激光瞄准，便于看清它们的射击方向。',
    'Replaces CPG-48 Snapper, Includes 3 camo options': '替换 CPG-48「工兵」，含 3 种迷彩选项',
    'Replaces DP-8 or RS-67 with custom reach style ODST': '把 DP-8 或 RS-67 替换为自定义的致远星风格 ODST',
    "Road wheels that work like a tank's: the game's tanks rest on their bump stops, so the wheels can't move. Here each wheel rests part-way down a longer travel and follows the ground, keeping its track down, well damped; the hull is no longer thrown sideways when one track unloads. The tanks ride a little higher than in the game.": '像真实坦克那样工作的负重轮：原版坦克压在缓冲块上，轮子根本无法活动。本模组让每个轮子在更长的行程中半悬并贴合地面，履带始终压地、阻尼充分；单侧履带卸载时车体不再被甩向一侧。车体会比原版略高一点。',
    "Skip armor they can't hurt and dropships; the game decides the order.": '跳过打不动的装甲和运输艇；攻击顺序由游戏决定。',
    "Smarter, safer aiming for your guard dog (Guard Dog, Rover, K-9), your sentries and the resupply pod and Supply FRV guns. They never shoot through you or your teammates, skip the dead, cover and armor they can't hurt, and pick the right targets. The Tesla Tower stops zapping you. Optional targeting laser. Each part can be turned on or off in the options (also in game with Mod Options Menu). Requires Bingus Shared Loader v15 or newer.": '让护卫犬（护卫犬、漫游者、K-9）、哨戒炮以及补给舱和补给 FRV 的机枪瞄得更聪明、更安全。它们绝不穿过你或队友开火，跳过尸体、掩体和打不动的装甲，并选出正确的目标。特斯拉塔不再电击你。可选瞄准激光。每个部分都能在选项里单独开关（也可在游戏内「模组选项菜单」里调整）。需要 Bingus Shared Loader v15 或更新版本。',
    'The Bastion and Maelstrom, from the gunner seat.': '堡垒与漩涡，可在炮手座驾驶。',
    "The game's distance, 1.4 m up (the game: 2 m).": '与原版一致的距离，高度 1.4 米（原版为 2 米）。',
    "The guard dog and sentry improvements (safety, closest threat first, no shooting the dead, no shooting into cover, Guard Dog range, Rover fire spreading; sentries that don't fire through you or swing their fire across you, stop firing into walls, deal with enemies at their feet first, a Laser Sentry that sets enemies alight and moves on like the Rover and cools down before it burns out, and a Tesla Tower that leaves helldivers and enemies next to them alone). Keep this on.": '护卫犬与哨戒炮的整体改进（安全保护、优先最近的威胁、不射击尸体、不朝掩体开火、护卫犬射程、漫游者火焰蔓延；哨戒炮不会穿过你开火或把弹道扫过你、不会对着墙射击、优先处理脚下的敌人；激光哨戒炮能点燃敌人并像漫游者那样转移目标、过热前会先冷却；特斯拉塔不再电击绝地潜兵及其旁边的敌人）。请保持开启。',
    "The right target first; they may shoot armor they can't hurt.": '优先攻击正确的目标；可能对打不动的装甲开火。',
    'Toggleable helmet flood light with two switchable profiles. L toggles, N switches mode while the lamp is on; both keys are rebindable in the ini, or in game with Mod Bindings Menu v2. The hotkeys are ignored while the in-game chat box is open. Requires Bingus Shared Loader v15 or newer.': '可开关的头盔泛光灯，带两套可切换配置。按 L 开关，开灯时按 N 切换模式；两个按键都可在 ini 里重绑，也可用游戏内的「模组按键菜单 v2」重绑。游戏内聊天框打开时热键会被忽略。需要 Bingus Shared Loader v15 或更新版本。',
    'Twice as quick: the tanks snap into turns.': '转向快一倍：坦克入弯干脆利落。',
    'Twice the grip: the tanks stick to the ground.': '抓地力翻倍：坦克稳稳咬地。',
    "Visibility Boost when you're in need!": '危难时刻，看得更清！',
    "Weapon setting icons only - fire mode, function, scope zoom - beside the game's weapon panel. Fixed brightness, and they hide when that panel hides.": '只显示武器状态图标（射击模式、功能、倍镜）于游戏武器面板旁。亮度固定，随该面板一同隐藏。',
    'Aggro Counter v1.3': '仇恨计数 v1.3',
    'Armored Overhaul 3.0.1': '装甲大修 3.0.1',
    'Better Map Markers': '更好的地图标记',
    'Bingus Shared Loader - v18': 'Bingus 共享加载器 - v18',
    'Castle ODST': 'Castle 地狱伞兵',
    'Concept Mech': '概念机甲',
    'Enhanced Sentries Revamped': '强化哨戒炮重制版',
    'GL-52 Shooter Exclusion v0.1.2': 'GL-52 射击者排除 v0.1.2',
    'Glowing Supply Icons v4.2': '发光补给图标 v4.2',
    'Helmet Headlamp': '头盔头灯',
    'Menacing Heavy Weapons - 1.7.4': '威压重型武器 - 1.7.4',
    'Muzzle Flash Smoke Remover 3.2.2': '枪口硝烟移除 3.2.2',
    'ODST Loner': 'ODST 独行者',
    'Smarter Guard Dogs & Sentries 4.6.1': '更聪明的护卫犬与哨戒炮 4.6.1',
    'Super Laser Sights for Turrets and Drones': '炮塔与无人机激光瞄准',
    'Vanilla Plus Megapack - v35': 'Vanilla Plus 合集 - v35',
    'GNH Transmog 界面汉化（可选）': 'GNH Transmog 界面汉化（可选）',
    'GNH 简体中文汉化包': 'GNH 简体中文汉化包',
    'Mod Bindings Menu v2.1': '模组按键菜单 v2.1',
    'Mod Bindings Menu': '模组按键菜单',
    'Native MODS tab for mod bindings': '用于模组按键的原生 MODS 分页',
    'Adds a native MODS tab to the keyboard and controller binding pages: up to 36 mod bindings grouped by mod, with every activation type and controller buttons. Requires Bingus Shared Loader v17+.': '在键盘与控制器按键设置页新增原生「MODS」分页：最多 36 个模组按键，按模组分组，支持所有触发方式与手柄按键。需要 Bingus Shared Loader v17+。',
    'ARES - Official Arsenal Mod': 'ARES - Arsenal 官方模组',
    'Replaces AD-26 Armor, B-01 Helmet, CE-81 Armor, and CE-81 Helmet with Commander Ares, the Arsenal Mod Manager mascot character. Includes multiple visor options for the helmets.': '把 AD-26 护甲、B-01 头盔、CE-81 护甲与 CE-81 头盔替换为 Arsenal 模组管理器的吉祥物角色「指挥官 ARES」。头盔含多种面罩样式。',
    'AD-26 // Armor': 'AD-26 // 护甲',
    'Replaces AD-26 Armor': '替换 AD-26 护甲',
    'B-01 // Helmet': 'B-01 // 头盔',
    'Replaces B-01 Helmet': '替换 B-01 头盔',
    'CE-81 // Armor': 'CE-81 // 护甲',
    'Replaces CE-81 Armor': '替换 CE-81 护甲',
    'CE-81 // Helmet': 'CE-81 // 头盔',
    'Replaces CE-81 Helmet': '替换 CE-81 头盔',
    'Gold Shark Visor': '金色鲨鱼面罩',
    'Gold Visor': '金色面罩',
    'Silver Shark Visor': '银色鲨鱼面罩',
    'Silver Visor': '银色面罩',
    'Nightfall Operator Body Armors (B-01) (Original)': '暗夜行动员护甲（B-01）（原版）',
    'FRV Anti-Flip': 'FRV 防翻车',
    'HD2 SmoothBoot': 'HD2 平滑启动',
    'Requires Bingus Shared Loader v15 or newer / API 1. Enable both and deploy.': '需要 Bingus Shared Loader v15 或更新版本 / API 1。两者都启用后部署。',
    'HD2 C4 Quick Actions 1.13': 'HD2 C4 快捷操作 1.13',
    'C4 throw and detonate actions with customizable mouse and controller bindings, Manual/Contact detonation modes, passenger throwing and automatic reload. Requires Mod Bindings Menu v2 and Bingus Shared Loader v17+.': 'C4 投掷与引爆操作，可自定义鼠标与手柄按键；含手动/接触两种引爆模式、载员投掷与自动装填。需要「模组按键菜单 v2」与 Bingus Shared Loader v17+。',
    'Objective Tracker': '目标追踪器',
    'Locate side objectives, enemy installations and specimen samples with clear icons, live distances and compass directions. Completed objectives disappear automatically as the game confirms them. Customize the panel position, size, transparency, colors and target filters. Choose to keep the panel visible or show it only with the tactical map. See who is carrying a head, egg or larva with squad tags beside the item.': '用清晰的图标、实时距离与罗盘方位定位支线目标、敌人设施与样本。目标完成后会随游戏确认自动消失。可自定义面板位置、大小、透明度、颜色与目标筛选；可选择常驻显示，或只在战术地图上显示。物品旁的小队标记会显示谁拿着头颅、虫卵或幼虫。',
    'Smarter Guard Dogs & Sentries 4.6.3': '更聪明的护卫犬与哨戒炮 4.6.3',
    'HD2 Transmog Foundation 0.2.1 (Experimental)': 'HD2 Transmog 基础组件 0.2.1（实验版）',
    'HD2 Transmog Foundation 0.2.0 (Alpha)': 'HD2 Transmog 基础组件 0.2.0（Alpha）',
    'Show Badge': '显示徽章',
    'Show the badge beside the compass. Same as Ctrl+Shift+O.': '在罗盘旁显示徽章。同 Ctrl+Shift+O。',
    'Where the badge sits. Beside the compass it grows away from it when enlarged.': '徽章所在位置。放大时会向背离罗盘的方向扩展。',
    'Left of Compass': '罗盘左侧',
    'Right of Compass': '罗盘右侧',
    'Under Warning Banners': '警告横幅下方',
    'Badge size. It shrinks by itself if it does not fit beside the compass.': '徽章尺寸。若罗盘旁放不下会自动缩小。',
    'Move Right': '向右移动',
    'Nudge the badge sideways, in 1440p pixels (negative = left). Same as Ctrl+Shift+J / L.': '左右微调徽章，单位 1440p 像素（负值 = 向左）。同 Ctrl+Shift+J / L。',
    'Move Down': '向下移动',
    'Nudge the badge up or down, in 1440p pixels (negative = up). Same as Ctrl+Shift+I / K.': '上下微调徽章，单位 1440p 像素（负值 = 向上）。同 Ctrl+Shift+I / K。',
    'Nearby Cell': '附近计数',
    'Radar: every live enemy within the nearby radius of you, whatever it is doing.': '雷达：附近半径内所有存活敌人，无论它在做什么。',
    'Searching Cell': '搜索计数',
    'Eye: enemies searching for you (lost sight of you, alerted, dropping in, emerging).': '眼睛：正在搜索你的敌人（跟丢你、进入警戒、空降、钻出地面）。',
    'On You Cell': '锁定你',
    'Reticle: enemies fighting you, or the vehicle you are in.': '准星：正在攻击你或你所乘载具的敌人。',
    'Teammates Cell': '锁定队友',
    'People: enemies fighting your teammates.': '人物：正在攻击你队友的敌人。',
    'When Nothing Is Counted': '计数全为零时',
    'What the badge does while every shown number is 0.': '所有显示数字均为 0 时，徽章的表现。',
    'Background Opacity': '背景不透明度',
    'Red From': '变红阈值',
    'Enemies on you from which the on-you number and bar turn red.': '锁定你的敌人达到该数量时，「锁定你」的数字与进度条变红。',
    'Nearby Radius (m)': '附近半径（米）',
    'How far the nearby cell counts enemies.': '附近计数统计敌人的最远距离。',
    'Ctrl+Shift Keys': 'Ctrl+Shift 快捷键',
    'The Ctrl+Shift keys that show, resize and move the badge.': '用于显示、缩放和移动徽章的 Ctrl+Shift 快捷键。',
    'Let HUD Mods Replace It': '允许 HUD 模组接管',
    'Another HUD mod may hide this badge while it shows the same numbers itself.': '其他 HUD 模组可隐藏此徽章，改由它自己显示相同数字。',
    'Diagnostic Log': '诊断日志',
    'Detailed log (Logs/AggroCounter.log) for bug reports; F8 then marks the moment. Leave it off otherwise.': '用于反馈问题的详细日志（Logs/AggroCounter.log）；F8 可标记当前时刻。平时请保持关闭。',
    'ARMORED OVERHAUL': '装甲大修',
    "The Bastion and Maelstrom turrets turn all the way round like a main battle tank. The Maelstrom's missile pods and smoke launchers turn with it. Only you see the new turrets, and their armor always looks undamaged.": '堡垒与漩涡的炮塔可像主战坦克一样整圈旋转，漩涡的导弹发射巢与烟雾发射器会随之转动。新炮塔只有你能看到，且其装甲始终显示为未受损。',
    "Drive from the gunner seat when the driver seat is empty: your movement keys drive and a driver panel shows gear, rpm, speed and fuel. F sounds the horn; Mouse 3 pops the Maelstrom's smoke. Controller: the left stick drives, its click is the horn, the right stick click pops smoke. Set your own keys with the Mod Bindings Menu. A teammate who takes the wheel drives. Pick which vehicles.": '驾驶座无人时可从炮手座驾驶：用移动键开车，并显示档位、转速、速度与燃料的驾驶面板。F 鸣笛；鼠标中键释放漩涡的烟雾。手柄：左摇杆驾驶，按下左摇杆鸣笛，按下右摇杆放烟。可用 Mod Bindings Menu 自定义按键。队友上车驾驶时由队友操控。可选择适用载具。',
    'FRV': 'FRV',
    "A small outline of your vehicle shows where the gun points compared to the hull, colored by health (blue to red). Works in the Bastion, the Maelstrom, the M-102 FRV and the M-103 Supply FRV, in any seat; the FRVs' tires each show their own health and go clear when popped. Only you see it.": '用小型轮廓显示载具火炮相对车体的指向，并按血量着色（蓝到红）。适用于堡垒、漩涡、M-102 FRV 与 M-103 补给 FRV 的任意座位；FRV 的每个轮胎单独显示血量，爆胎后变透明。只有你能看到。',
    'SMARTER GUARD DOGS & SENTRIES': '更聪明的护卫犬与哨戒炮',
    "How your dogs and sentries choose what to shoot. Armor Intelligence: they leave alone armor they can't hurt, fire only short bursts at Heavy Devastators, and no sentry wastes ammo on dropships. Target Prioritization: your dog goes for the closest threat to you first; your sentries deal with enemies at their feet, Gunships and the armor that suits the gun first. Turn off to leave both to the game.": '你的护卫犬与哨戒炮如何选择射击目标。装甲识别：放过打不穿的装甲目标，对重型毁灭者只做短点射，哨戒炮不会把弹药浪费在运输舰上。目标优先：护卫犬优先攻击离你最近的威胁；哨戒炮优先处理脚下的敌人、炮艇以及适合其火力的装甲。关闭后两项都交还给游戏。',
    "Who your dog and your sentries never fire through: they hold fire while that helldiver is in their line of fire, don't swing their fire across them, mortars and the rocket sentry leave enemies next to them alone, and the Tesla Tower doesn't zap them or arc into them. Turn off at your own risk: they will fire through anyone. Everything else keeps working.": '你的护卫犬与哨戒炮绝不误伤的对象：当该潜兵位于射线上时它们会停火，不会把火力扫过对方，迫击炮与火箭哨戒炮会放过紧挨着对方的敌人，特斯拉塔也不会电到或电弧到对方。关闭后果自负：它们会朝任何人开火。其余功能不受影响。',
    "Laser out of the barrel of your guard dog and your sentries (not the mortars) toward their targets, shown only on your screen: green while they fire, flashing red when the safety stops a shot, flashing yellow when the dog's target goes out of sight. The Tesla Tower shows its reach as a yellow ring. Line: thin, hidden by walls. Glow: a soft beam that shows through walls.": '从护卫犬与哨戒炮（迫击炮除外）炮口射向目标的激光，仅你可见：开火时为绿色，被安全防护拦下时闪红，护卫犬丢失目标时闪黄。特斯拉塔以黄圈显示其作用范围。细线：纤细，会被墙挡住。辉光：柔和光束，可透过墙壁看到。',
    'Show objective tracker': '显示任务目标追踪',
    'Show only while map is open': '仅在打开地图时显示',
    'Display the tracker with the tactical map. The panel also appears in ESC for positioning and resizing.': '与战术地图一同显示追踪面板。该面板也会出现在 ESC 菜单中，供你调整位置与大小。',
    'Maximum visible targets': '最多显示目标数',
    'Show the nearest targets, sorted by distance. Panel height also limits how many rows fit.': '显示最近的目标，按距离排序。面板高度也会限制可容纳的行数。',
    'Maximum distance (meters)': '最大距离（米）',
    'Direct distance from your Helldiver to loaded objectives.': '从你的绝地潜兵到已加载目标的直线距离。',
    'Text and icon size (%)': '文字与图标大小（%）',
    'Set the text and icon size. Resizing the panel keeps this size and changes how many targets fit.': '设置文字与图标大小。调整面板尺寸会保留该字号，并改变可容纳的目标数量。',
    'Background opacity (%)': '背景不透明度（%）',
    'Icon and distance colors': '图标与距离颜色',
    'Objective colors': '目标配色',
    'Helldiver gold': '绝地潜兵金',
    'Ice white': '冰白',
    'Row spacing': '行间距',
    'Compact': '紧凑',
    'Comfortable': '宽松',
    'Support and retrieval objectives': '支援与回收类目标',
    'Radar stations, SEAF artillery, SAM sites, escape pod data and mutant larvae.': '雷达站、SEAF 火炮、防空导弹阵地、逃生舱数据与变异幼虫。',
    'Hostile nests and installations': '敌方巢穴与设施',
    'Research objective sites': '研究类目标地点',
    'Specimen pickups': '样本拾取物',
    'Show Automaton heads and mutated eggs with distance and direction.': '显示自动人形头颅与变异卵的距离和方向。',
    'Show item carrier': '显示物品携带者',
    'Show the carrier squad tag for Automaton heads, mutated eggs and mutant larvae.': '为自动人形头颅、变异卵与变异幼虫显示携带者的小队标签。',
    'Hide completed objectives': '隐藏已完成目标',
    'Hide objectives after the game reports completion. Completion affects only your HUD.': '当游戏报告目标完成后将其隐藏。该完成状态只影响你自己的 HUD。',
    'Hide destroyed sites': '隐藏已被摧毁的地点',
    'For sites without a readable objective state, hide the entry when every observed structure is dead or removed. Native objective state takes priority when available.': '对于无法读取任务状态的地点，当观察到的所有结构均已被摧毁或移除时隐藏该条目。若可读取原生任务状态，则以原生状态为准。',
    'Show panel aboard ship': '在飞船上也显示面板',
    'Detailed logging': '详细日志',
    'Write objective state details to the local log for troubleshooting.': '将任务状态详情写入本地日志，便于排查问题。',
    'HD2 Transmog': 'HD2 幻化',
    'Preview style': '预览风格',
    'Choose the lighting for generated previews. HD2 uses the approved rim lighting; Studio emphasizes front detail. Both styles stay cached. Items without an author choice use HD2.': '选择生成预览所用的光照。HD2 使用官方认可的轮廓光；Studio 更强调正面细节。两种风格的缓存都会保留。作者未指定时使用 HD2。',
    "Mod author's choice": '作者指定',
    'Force HD2': '强制 HD2',
    'Force Studio': '强制 Studio',
    'Armory 3D preview': '军械库 3D 预览',
    'Full render': '完整渲染',
    'Game default': '游戏默认',
    "Full render draws the large Armory model through the game's full pipeline, with hair and the lighting of the generated previews. It needs temporal anti-aliasing; without it, and with Game default, the game draws the model itself.": '完整渲染会通过游戏的完整渲染管线绘制大型军械库模型，包含头发以及生成预览所用的光照。它需要开启时间抗锯齿；若未开启，或者选择「游戏默认」，则由游戏自行绘制模型。',
    'Regenerate previews': '重新生成预览',
    'Keep cached images': '保留缓存图像',
    'Regenerate now': '立即重新生成',
    'Apply Regenerate now to refresh generated previews for the selected style. Requires a working renderer and an open Armory item list. Cached images remain available if rendering is unavailable.': '选择「立即重新生成」可用当前风格刷新已生成的预览。需要渲染器可用且军械库物品列表已打开。若渲染不可用，仍会保留缓存图像。',
    'SHOW / HIDE BADGE': '显示/隐藏徽章',
    'BADGE BIGGER': '放大徽章',
    'BADGE SMALLER': '缩小徽章',
    'MOVE BADGE UP': '上移徽章',
    'MOVE BADGE DOWN': '下移徽章',
    'MOVE BADGE LEFT': '左移徽章',
    'MOVE BADGE RIGHT': '右移徽章',
    'Select Next Transmog Piece': '选择下一件幻化部件',
    'Next Transmog Variant': '下一个幻化变体',
    'Previous Transmog Variant': '上一个幻化变体',
    'Refresh Transmog Look': '刷新幻化外观',
    'Custom Variant': '自订变体',
    'Shallow Water Diving': '浅水潜行',
    'Better Lobby Management': '大厅管理',
    'No variant selected': '未选择任何变体',
    '1  Resource ID': '1  资源 ID',
    '2  Icon material': '2  图标材质',
    '3  Texture binding': '3  贴图绑定',
    '4  Configured icon': '4  已配置图标',
    'Kick Test': '踢人测试',
    'Promote Notice': '提升通知',
    'Ship Station Hotkeys': '舰内站点快捷键',
    'Markers For MineField': '雷区标记',
    'All-In-One Pack': '整合包（一包包含全部标记）',
    'Simple Marker': '简易标记',
    'Add little cones above each mine\n\nCaution: Disable "Detailed Marker" if using this': '在每颗地雷上方显示小圆锥\n\n注意：使用本项时请关闭「详细标记」',
    'Detailed Marker': '详细标记',
    'Add detailed icons above each mine\n\nCaution: Disable "Simple Marker" if using this': '在每颗地雷上方显示详细图标\n\n注意：使用本项时请关闭「简易标记」',
    'Game Original Color': '游戏原版配色',
    'Custom Color': '自定义配色',
    'Marker For Automaton Mine': '自动人形地雷标记',
    'Add symbol icon above Automaton mine': '在自动人形地雷上方显示符号图标',
    'Lure Mine': '诱饵雷',
    'Add explosion icon above TM-1 Lure Mine': '在 TM-1 诱饵雷上方显示爆炸图标',
    'Damaged Hellbomb': '受损地狱火炸弹',
    'Add Hellbomb icon above Damaged Hellbomb \n(Randomly spawn in maps)\n\nAdd Emissive VFX on prong/top parts of Hellbomb\n(For clearer identification)': '在受损地狱火炸弹上方显示地狱火炸弹图标\n（在地图中随机刷新）\n\n为地狱火炸弹的支脚与顶部添加自发光特效\n（便于更清晰地辨认）',
    'G/40-K Meltamine': 'G/40-K 熔融雷',
    'Add WH40K icon above G/40-K Meltamine\n\nAdd Emissive VFX on surface of Meltamine\n(For clearer identification)': '在 G/40-K 熔融雷上方显示 WH40K 图标\n\n为熔融雷表面添加自发光特效\n（便于更清晰地辨认）',
    'Beacon Custom VFX': '信标自定义特效',
    'Beacon beam replacment': '替换信标光柱特效',
    'Blue Beacon': '蓝色信标',
    'Blue V1': '蓝色 V1',
    'Blue V2 (Rock and Stone)': '蓝色 V2（Rock and Stone）',
    'Red Beacon': '红色信标',
    'Red V1': '红色 V1',
    'Red V2 (Vanilla plus)': '红色 V2（原版增强）',
    'C-Rig Runtime(ShareLoader)': 'C-Rig 骨骼运行时（共享加载器）',
    'Runtime': '运行时',
    'MUST SELECT': '必须选中',
    'Rigs & Physics': '骨骼与物理',
    'C-Rig runtime': 'C-Rig 运行时',
    'OFF restores the current pose once, then suspends tracking, rigs, IK, animations, physics, statistics and profiling. Individual choices are preserved. ON binds the current scene again.': '关闭后会先恢复一次当前姿势，然后暂停追踪、骨骼、IK、动画、物理、统计与性能分析；各项独立选项都会保留。开启后重新绑定当前场景。',
    'Custom rigs': '自定义骨骼',
    'Enable authored armor retargeting for all matching pieces. Physics is controlled separately.': '为所有匹配的部件启用作者制作的盔甲骨骼替换。物理由单独的开关控制。',
    'Custom animations': '自定义动画',
    'Play baked bone Actions before physics. Matching mesh pieces share one clock. Turning this off restores their input pose.': '在物理运算之前播放预烘焙的骨骼动作。匹配的网格部件共用同一时钟。关闭后会恢复它们原本的输入姿势。',
    'All physics': '全部物理',
    'Master switch for physics only; custom Actions keep playing. Layout and individual system choices are preserved while this is OFF.': '只控制物理的总开关；自定义动作仍会继续播放。关闭期间，布局与各子系统的独立选项都会保留。',
    'Statistics overlay': '统计信息浮层',
    'Show per-layout animation groups and active pieces at the upper right. Counts refresh once per second. Does not change rigs or physics.': '在右上角显示各布局的动画分组与当前生效的部件。计数每秒刷新一次。不会改变骨骼或物理。',
    'Hand IK': '手部 IK',
    'OFF: no hand correction. ON: both hands follow original animation targets. AUTO: correct each hand only while weapon-bone contact is detected. Unconfirmed first-person right-hand contact stays OFF.': '关闭：不做手部修正。开启：双手跟随原动画目标。自动：仅在检测到武器与骨骼接触时修正对应的那只手；第一人称下未经确认的右手接触保持关闭。',
    'Auto': '自动',
    'Vanilla Plus Megapack - v37': 'Vanilla Plus 合集 - v37',
    "Choose any of the seventeen bundled mods in this pack's Options menu in Arsenal or HD2MM. Requires the separate Bingus Shared Loader v18. Disable standalone copies of features you want turned off. Close the game, select your options, then Purge / Deploy. With default Arsenal priority put the loader last.": '在 Arsenal 或 HD2MM 的选项菜单里任选本包内含的十七个模组。需要单独安装 Bingus Shared Loader v18。想关掉的功能，请先禁用对应的独立模组。关闭游戏、选好选项后再执行 Purge / Deploy（清除部署 / 部署）。使用 Arsenal 默认优先级时，请把共享加载器放在最后。',
    'Better Stratagem Bounce': '战备球弹射优化',
    'Allows stratagem balls to stick on more usable surfaces.': '让战略配备球能附着在更多可用的表面上。',
    'Hellpod Steering Unlocked': '地狱舱转向解锁',
    'Removes the hellpod steering restriction near high ground.': '解除地狱舱在高地附近无法转向的限制。',
    'Reinforcement Beacons Fixed': '增援信标修正',
    'Centers queued reinforcements over their beacon or solo anchor.': '把排队中的增援落点对准信标，单人时对准自身锚点。',
    'Consistent Vaulting': '翻越判定稳定化',
    'Adds fresh obstacle checks, higher ledge detection and bounded steep-surface support.': '新增障碍检测、提高边缘检测高度，并支持一定限度内的陡坡翻越。',
    'Preserves the standing water reference during a local airborne dive; the depth limit is adjustable in Mod Options Menu.': '在本地鱼跃入水时保留站立水面的参照点；深度上限可在「模组选项菜单」里调整。',
    'Sentry Aim Retention': '哨戒炮瞄准保持',
    'Retains sentry aim and improves target handoffs and firing checks.': '保持哨戒炮的瞄准，并改善目标切换与开火判定。',
    'Enemy Collision Synchronized': '敌人碰撞同步修正',
    'Aligns displaced corpse collision and curbs renewed movement after large remote corpses settle.': '修正位置被移动的尸体碰撞，并抑制远处大型尸体落定后的二次移动。',
    'Controllable Hover Pack': '悬浮背包可控下降',
    'Press the Jump Pack action again to descend early with native landing assistance.': '再次按下跳跃背包键即可提前下降，并使用与原版一致的落地辅助。',
    'Know Your Constellation': '敌情预测',
    'Shows every enemy a mission can spawn, weighted by how often it spawns, on the war table and the briefing screen.': '在战争桌与任务简报界面显示该任务可能刷出的所有敌人，并按刷新频率加权。',
    'Armory Preview Cache': '军械库预览缓存',
    'Caches equipment thumbnails and preloads assets in Armory and mission briefing.': '缓存装备缩略图，并在军械库与任务简报中预加载资源。',
    'Clickable Scrollbars': '可点拖滚动条',
    'Smoothly drag equipment and Career scrollbars, even with the pointer away from the track.': '可以平滑拖动装备与生涯界面的滚动条，指针离开滑轨也能继续拖。',
    'Arc Thrower Revamped': '电弧枪重制',
    'Hold the fire button to keep the Arc Thrower firing.': '按住开火键即可让电弧枪持续射击。',
    'Ship station shortcuts: Tab map, F1 Armory, F5 Control Center, F6 Ship Management, F7 Stratagem Hero, F8 instant Hellpod entry. Enable Mod Bindings Menu to rebind them.': '舰内站点快捷键：Tab 地图、F1 军械库、F5 控制中心、F6 舰船管理、F7 战略配备英雄、F8 立即进入地狱舱。启用「模组按键菜单」可自定义这些按键。',
    'Flame Damage Fixed': '火焰伤害修正',
    "Fixes the Lumberer's and Flame Sentry's flame: two flame parts spawn again, it starts at the Cremator's distances and no longer hits the weapon that fires it, while still hitting Chargers and every other target.": '修正伐木者与喷火哨戒炮的火焰：重新生成两段火焰，射程起始距离与焚化者一致，不再烧到开火的武器本身，同时仍能命中冲锋虫及其它目标。',
    'Mod Options Menu': '模组选项菜单',
    'Adds a native MODS tab to the Options screen, where mods such as Shallow Water Diving offer their settings.': '在设置界面加入原生的「模组」标签页，浅水潜行等模组可在这里调整设置。',
    'Adds a native MODS tab to the keyboard and controller binding pages, where mods such as Ship Station Hotkeys offer rebindable keys.': '在键盘与手柄的按键绑定页加入原生「模组」标签页，舰内站点快捷键等模组可在这里改键。',
    "Host tools in the escape menu: DISBAND SQUAD, PROMOTE, which moves the whole squad to the new host's ship, and CANCEL SOS in a mission (only the host needs the mod). Also a 5-second Galactic Map lobby scanner and an own-continent lobby filter.": 'ESC 菜单里的房主工具：解散小队、提升房主（把整支小队转移到新房主的飞船上）、任务中取消 SOS（只有房主需要装本模组）。另有 5 秒一次的银河地图房间扫描，以及「仅同大陆房间」筛选。',
    'Armored Overhaul 3.2.0': '装甲大修 3.2.0',
    'Longer road wheel travel for the Bastion and Maelstrom: the wheels drop into dips so the tracks stay on the ground, firmer damping settles the hull quickly after rocks and bumps, and a lower center of gravity makes them harder to tip. The tanks ride 0.1 m higher than in the game.': '加长堡垒与漩涡的负重轮行程：轮子会陷进凹坑，让履带贴住地面；更强的阻尼使车体在过石与颠簸后迅速稳定；更低的重心让它们更难翻覆。车体会比原版高 0.1 米。',
    "Half a meter of wheel travel, damped about half again as much as the game's; the center of gravity as high off the ground as in the game.": '半米的轮子行程，阻尼约为原版的 1.5 倍；重心高度与原版一致。',
    "A little less travel, slightly firmer springs, about twice the game's damping and the lowest center of gravity: the calmest ride, very hard to tip.": '行程略短，弹簧略硬，阻尼约为原版两倍，重心最低：乘坐最平稳，极难翻车。',
    "The Bastion and Maelstrom turrets turn like a main battle tank's: all the way round, or half way. The Maelstrom's missile pods and smoke launchers turn with it. The turret wears your camo and shows damage like the rest of the tank. Only you see the turning turrets.": '堡垒与漩涡的炮塔像主战坦克一样旋转：可整圈旋转，或半圈。漩涡的导弹舱与烟雾发射器会跟着转。炮塔会继承你的迷彩，并像车体其它部分一样显示损伤。转动效果只有你自己看得到。',
    '360 (all the way round)': '360 度（整圈旋转）',
    'The turret turns all the way round.': '炮塔可以整圈旋转。',
    '180 (90 each side)': '180 度（左右各 90 度）',
    'The turret turns up to 90 degrees either side of straight ahead; the gunner view stops where the gun does.': '炮塔最多向正前方左右各偏转 90 度；炮手视角会随火炮一起停下。',
    "How fast the Bastion and Maelstrom turrets turn (the game: 25 degrees a second), and the gunner view's left/right turning with them. Works with or without MBT Turrets.": '堡垒与漩涡炮塔的旋转速度（原版为每秒 25 度），以及炮手视角的左右跟随速度。无论是否启用「坦克炮塔全向旋转」都有效。',
    'Fast (x2)': '快（×2）',
    'Very fast (x3)': '极快（×3）',
    '75 degrees a second.': '每秒 75 度。',
    "How fast the Bastion and Maelstrom guns move up and down (the game: 35 degrees a second), and the gunner view's up/down turning with them.": '堡垒与漩涡火炮的俯仰速度（原版为每秒 35 度），以及炮手视角的上下跟随速度。',
    'Drive from the gunner seat when the driver seat is empty: your movement keys drive, shift and CTRL change gear, Space is the handbrake and the gun works as normal. F sounds the horn; in the Maelstrom, Mouse 3 pops smoke. On a controller the left stick drives, its click sounds the horn and the right stick click pops smoke. A teammate who takes the wheel drives as normal, and getting out while it rolls brakes it to a stop. With the Mod Bindings Menu you can set your own keys for all of these (controls, tab MODS). Pick which vehicles.': '驾驶座空着时，可以在炮手位开车：你的移动键负责驾驶，Shift 与 Ctrl 换挡，空格是手刹，火炮照常使用。F 鸣笛；在漩涡上鼠标中键放烟。手柄则是左摇杆驾驶、按下左摇杆鸣笛、按下右摇杆放烟。队友坐上驾驶座后照常开车；车辆还在滑动时下车会自动刹停。配合「模组按键菜单」可以为以上所有操作自定义按键（按键设置 → 模组标签页）。可选择对哪些载具生效。',
    'Driver Panel': '驾驶员面板',
    "Needs Gunner Drive. While you drive from the gunner seat, a panel like the driver's own HUD shows the gear, rpm, speed, fuel and the Maelstrom's smoke rounds. It only shows while you are the one driving: never when a teammate sits in the driver seat or another player's game runs the vehicle. Only you see it. With the Mod Options Menu you can turn it off in game.": '需要先启用「炮手位驾驶」。你从炮手座开车时，会显示一块类似驾驶员 HUD 的面板，上面有档位、转速、速度、燃料以及漩涡的烟雾弹数量。只有你在驾驶时才显示——队友坐在驾驶座、或车辆由其他玩家的游戏控制时都不会出现。只有你自己看得到。配合「模组选项菜单」可以在游戏内关掉它。',
    'Puts the Bastion and Maelstrom gunner camera lower and further back so you see more around the tank. It stays behind the turret as it turns. The pick is where the camera starts: scroll the mouse wheel to move it closer or further back, and from the closest point scroll on to zoom in on the crosshair (shown as x2.4 and so on). With the Mod Bindings Menu you can also set Zoom In / Zoom Out keys, for a controller too.': '把堡垒与漩涡的炮手镜头放低并后移，让你看到坦克周围更多区域；炮塔旋转时镜头会跟在后面。所选档位是镜头的起始位置：滚轮可以前后拉近拉远，拉到最近后继续滚则会对着准星放大（显示为 x2.4 等）。配合「模组按键菜单」还能设置放大 / 缩小按键，手柄也支持。',
    "Keeps the M-102, M-103 and M-104 FRVs on their wheels over rough ground, jumps and hard turns: a firmer front, firmer damping, a lower center of mass, more grip and weight, and a little more ground clearance. Engine and steering stay the game's own.": '让 M-102、M-103、M-104 FRV 在崎岖地面、跳跃与急转弯时保持四轮着地：前部更硬、阻尼更强、重心更低、抓地与重量更大，并略微增加离地间隙。发动机与转向保持原版。',
    'Stays upright over rough ground, jumps and hard turns, with extra tire grip; 30% heavier.': '在崎岖地面、跳跃与急转弯时保持直立，轮胎抓地更强；重量 +30%。',
    'About half the change, with a little more grip: still lively, far less likely to roll; 17% heavier.': '改动约为一半，抓地略强：依然灵活，但翻车概率大幅降低；重量 +17%。',
    'The lowest center of mass, the firmest damping and the most grip, 45% heavier: very hard to tip.': '重心最低、阻尼最强、抓地最大，重量 +45%：极难翻车。',
    'Aggro Counter v1.4': '仇恨计数 v1.4',
    'Style': '样式',
    'How the badge looks.': '徽章的外观样式。',
    'Native': '原生',
    'Default. The game font and smooth icons, in line with the compass.': '默认。使用游戏字体与平滑图标，与罗盘风格一致。',
    'Pixel': '像素',
    'The original pixel badge.': '最初的像素风格徽章。',
    'Extended Pickup Icons': '拾取图标范围扩展',
    'Vanilla pickup icons: internal ViewDistance 35 for samples/gear, 20 for supplies, 15 for carry-ammo/warhead/SEAF shells. Build 25480438; Bingus Shared Loader v15+ required.': '让原版拾取图标显示得更远：样本与装备的内部视距 35，补给 20，随身弹药 / 弹头 / SEAF 炮弹 15。适用于构建 25480438；需要 Bingus Shared Loader v15+。',
    'Samples': '样本',
    'Common, rare, super and packaged samples: internal ViewDistance 35.': '普通、稀有、超级与打包样本：内部视距 35。',
    'Supplies': '补给',
    'Ammo, stims, grenade boxes and resupply packs: internal ViewDistance 20.': '弹药、兴奋剂、手雷箱与补给包：内部视距 20。',
    'Equipment & Mission Items': '装备与任务物品',
    'Non-primary weapons/backpacks: 35; carry-ammo, warhead and SEAF shells: 15; ordinary barrel/canister unchanged.': '非主武器的武器与背包：35；随身弹药、弹头与 SEAF 炮弹：15；普通油桶 / 气罐保持原版不变。',
    'EXO Stratagem Launcher': 'EXO 战略配备发射器',
    'Use the stock stratagem menu and launcher while piloting an Exosuit. Shows the launcher on the Exosuit you pilot, regardless of who called it in. Use separate movement and stratagem direction keys to move while the menu is open. Reopening the menu cancels the loaded beacon. Launched commands unload automatically; stock usage counts and cooldowns apply. Works standalone or with Bingus Shared Loader v15. A separate launcher-only mesh follows aim within elevation limits and parks during melee; the stationary base follows the cockpit, and the stock assembly remains visible after exit. Front tube recoils 20 cm on launch and returns over 0.24 seconds. No EXO body or headlight model replacement is included. Includes louder short arming audio on your own confirmed EXO launches and Activating while a beacon is loaded. Reopening the menu or exiting cancels the loaded beacon. Retains reduced polling and bounded launcher pose updates. Walking Barrage follows the launch direction.': '驾驶外骨骼机甲时也能使用原版的战略配备菜单与发射器。无论战略配备是谁投下的，只要你在驾驶这台机甲就会显示发射器。菜单打开时可用独立的移动键与方向键同时移动。重新打开菜单会取消已装填的信标。发射后的指令会自动卸下；使用次数与冷却沿用原版。可独立使用，也可配合 Bingus Shared Loader v15。另有一组独立的发射器模型，会在仰角限制内跟随瞄准，近战时收起；固定底座跟随驾驶舱，退出机甲后原版组件仍然可见。发射时前管后坐 20 厘米，0.24 秒内复位。本模组不替换机甲本体或头灯模型。包括：你自己确认的机甲发射、以及装填信标时按「激活」时的更响亮短促待发音效。重新打开菜单或退出会取消已装填的信标。保持了低轮询频率与有界的发射器姿态更新。「行走弹幕」会跟随发射方向。',
    'Enable the Exosuit stratagem launcher.': '启用外骨骼机甲的戰略配備发射器。',
    'Run-N-Gun v1.0.4': '边跑边打 v1.0.4',
    'Standalone shoot-while-running mod: sprint into firing to retain running speed, with the benefit tapering off as you move sideways for two-handed weapons. One-handed weapons can bypass the angle restriction. Includes configurable on-the-move sway and hipfire linger. Requires Bingus Shared Loader API 1. Mod Options Menu API 1 is optional; defaults work without it. Steam build 25480438.': '独立的「边跑边打」模组：冲刺中开火可保留奔跑速度；双手武器在侧向移动时效果会逐渐衰减，单手武器则可绕过角度限制。包含可调的移动中晃动与腰射延续。需要 Bingus Shared Loader API 1；「模组选项菜单」API 1 为可选，不装也能用默认值。适用于 Steam 构建 25480438。',
    'Tactical Combat Overhaul v1.7.9': '战术战斗大修 v1.7.9',
    'Movement and stamina that reward positioning: winded aim sways harder, crouching and going prone recover stamina faster, uphill running is slower and drains sprint stamina, downhill is quicker and cheaper, the wait before stamina refills is longer standing and shorter low, and your default melee hits harder the faster you charge in; successful vaults and ledge climbs can cost stamina only after the climb actually begins; an optional exhausted-melee guard prevents attacks on an empty stamina bar. Run and gun: sprint into firing and keep running forward, with the benefit tapering off as you turn sideways, at the cost of aim sway and stamina. Open ESC > MODS > TACTICAL COMBAT OVERHAUL and press APPLY. Requires Mod Options Menu API 1 and Bingus Shared Loader v18. Steam build 25480438.': '让移动与耐力更看重站位：气喘时瞄准晃动更大；蹲下与趴下能更快回复耐力；上坡奔跑更慢且消耗冲刺耐力，下坡更快更省力；耐力回充前的等待时间站立时更长、放低姿势时更短；冲得越快，默认近战伤害越高；翻越与攀爬只在动作真正开始后才消耗耐力；可选的「力竭近战保护」会阻止在耐力条为空时攻击。边跑边打：冲刺中开火并继续向前跑，转向侧面时效果逐渐衰减，代价是瞄准晃动与耐力消耗。打开 ESC > 模组 > TACTICAL COMBAT OVERHAUL 后点击「应用」。需要「模组选项菜单」API 1 与 Bingus Shared Loader v18。适用于 Steam 构建 25480438。',
    'Ricochet Overhaul v1.5.0': '跳弹大修 v1.5.0',
    'Shots that hit armor at a steep angle glance off: Off / Steeper Angles / Brutal Angles, plus a Debug setting (no penetration at any angle). Set on the MODS tab (Mod Options Menu) or in config.txt. Add-on for SHODAN Stat Editor (required). Requires Bingus Shared Loader v18+.': '以陡峭角度命中装甲的子弹会发生跳弹：关闭 / 更陡的角度 / 残酷角度，另有一个调试档（任何角度都不穿透）。可在「模组」标签页（模组选项菜单）或 config.txt 中设置。本模组是 SHODAN Stat Editor 的附加插件（必需）。需要 Bingus Shared Loader v18+。',
    'Bullet stratagem weapons overhaul 0.1.1': '实弹战略配备武器大修 0.1.1',
    'Bullet stratagem weapons overhaul': '实弹战略配备武器大修',
    "v1.1\nThat's a serious gun...\nBuffs MGs, Maxigun, Railgun and AMR.\n\nRequires Bingus Shared Loader v15+ / API 1 and HD2Runtime 0.28.1+ / API 1; install dependencies separately.": 'v1.1\n这才叫枪……\n强化机枪、重机枪、磁轨炮与反器材步枪。\n\n需要 Bingus Shared Loader v15+ / API 1 与 HD2Runtime 0.28.1+ / API 1；请单独安装这些依赖。',
    'Requires Bingus Shared Loader v15+ / API 1 and HD2Runtime 0.28.1+ / API 1; install dependencies separately.': '需要 Bingus Shared Loader v15+ / API 1 与 HD2Runtime 0.28.1+ / API 1；请单独安装这些依赖。',
    'Super Cardio': '超级体能',
    'Sprint while carrying heavy objects (SEAF shells, platinum bars, fusion batteries). Speeds are fixed to vanilla. Requires Bingus Shared Loader v18+ and HD2Runtime 0.28.1+, each installed as its own mod.': '搬着重物（SEAF 炮弹、铂金条、聚变电池）时也能冲刺。速度保持原版数值。需要 Bingus Shared Loader v18+ 与 HD2Runtime 0.28.1+，两者都需要单独安装。',
    'Hold sprint while carrying a heavy object to run': '搬着重物时按住冲刺键即可奔跑',
    'Bingus Shared Loader - v19': 'Bingus 共享加载器 - v19',
    'HD2 C4 Quick Actions 1.13.1': 'HD2 C4 快捷操作 1.13.1',
    'Adds what the vanilla HUD leaves out - a 3D weapon panel, ammo count and weapon icons on the weapon row, trajectory preview and squad status - built for readability at a glance.': '补上原版 HUD 缺少的部分——立体武器面板、武器栏上的弹药计数与武器图标、弹道预览以及小队状态——一切以「扫一眼就能看清」为目标。',
    '100%': '100%',
    '75%': '75%',
    '125%': '125%',
    '150%': '150%',
    '200%': '200%',
    'HD2Runtime 0.28.1': 'HD2Runtime 0.28.1',
    'Shared HD2Runtime API 1. Requires Bingus Shared Loader v15+ / API 1. Install once; no gameplay changes until a dependent mod requests them.': '共享的 HD2Runtime API 1。需要 Bingus Shared Loader v15+ / API 1。安装一次即可；在依赖它的模组提出请求之前，不会改变任何游戏内容。',
    'Shared runtime': '共享运行时',
    'Winded Sway': '气喘晃动',
    "EXHAUSTION: Uses the game's own exertion levels, the heavy-breathing state that builds while sprinting and peaks when stamina runs out. ON makes aim sway grow more at those levels. Rested aim is unchanged.": '力竭：沿用游戏自身的用力等级（冲刺时逐渐加重、耐力见底时达到峰值）。开启后这些等级会让瞄准晃动更明显；不喘时的瞄准不受影响。',
    'Winded Sway Strength': '气喘晃动强度',
    'EXHAUSTION (% of normal): Scales the EXTRA sway each exertion level adds. Normally the most winded level sways 1.6x; 250 makes it 2.5x, 500 makes it 4x. Levels with no extra sway stay unchanged. 100 = normal.': '力竭（正常值的百分比）：调整各用力等级额外增加的晃动。原本喘得最厉害时晃动为 1.6 倍；设为 250 变成 2.5 倍，500 变成 4 倍。本身没有额外晃动的等级不受影响。100 = 正常。',
    'Stance Recovery': '姿态回复',
    'RECOVERY: Changes how fast stamina refills in each stance. Normal full refill takes 7 s standing, 6 s crouched and 5 s prone. The wait before refilling starts is the Delay group below.': '回复：调整各姿态下耐力条的回充速度。原本站满需 7 秒、蹲下 6 秒、趴下 5 秒。开始回充前的等待时间见下方「延迟」组。',
    'Recovery Speed: Standing': '回复速度：站立',
    'RECOVERY (% of normal): Stamina refill speed while standing. 70 = a full refill takes 10 s instead of 7 s. Lower values push you to take a knee to catch your breath. 100 = normal.': '回复（正常值的百分比）：站立时的耐力回充速度。70 表示回满需要 10 秒（原本 7 秒）。数值越低越需要蹲下来喘口气。100 = 正常。',
    'Recovery Speed: Crouched': '回复速度：蹲下',
    'RECOVERY: Stamina refill speed while crouched. 150 = a full refill takes 4 s instead of 6 s. 100 = normal.': '回复：蹲下时的耐力回充速度。150 表示回满需要 4 秒（原本 6 秒）。100 = 正常。',
    'Recovery Speed: Prone': '回复速度：趴下',
    'RECOVERY: Stamina refill speed while prone. 150 = a full refill takes about 3.3 s instead of 5 s. 100 = normal.': '回复：趴下时的耐力回充速度。150 表示回满约需 3.3 秒（原本 5 秒）。100 = 正常。',
    'Recovery Delay': '回复延迟',
    'DELAY (seconds): The wait after using stamina (running, sliding, melee weapons, anything) before it refills. Game: 1.5 s in every stance. Your current stance sets the wait, and changing stance mid-wait counts once live stamina is confirmed (a moment of sprinting each mission).': '延迟（秒）：消耗耐力后（奔跑、滑铲、近战武器等）到开始回充之间的等待时间。原版各姿态均为 1.5 秒。等待时间由当前姿态决定；确认实时耐力后（每局先冲刺一下），等待中途换姿态也会立即生效。',
    'Delay: Standing': '延迟：站立',
    'DELAY: Seconds before stamina starts refilling while standing. Game default 1.5.': '延迟：站立时耐力开始回充前等待的秒数。原版默认 1.5。',
    'Delay: Crouched': '延迟：蹲下',
    'DELAY: Seconds before stamina starts refilling while crouched. Game default 1.5. Switching stance changes the wait right away.': '延迟：蹲下时耐力开始回充前等待的秒数。原版默认 1.5。换姿态会立即改变等待时间。',
    'Delay: Prone': '延迟：趴下',
    'DELAY: Seconds before stamina starts refilling while prone. Game default 1.5. Switching stance changes the wait right away.': '延迟：趴下时耐力开始回充前等待的秒数。原版默认 1.5。换姿态会立即改变等待时间。',
    'Slopes': '坡度',
    "SLOPES: Running uphill is slower and drains sprint stamina faster; running downhill is quicker and drains less. Speed uses the game's own slope settings; the stamina effect follows the slope you are actually running on.": '坡度：上坡更慢、冲刺耐力消耗更快；下坡更快、消耗更少。速度沿用游戏自身的坡度设置；耐力效果按你实际跑的坡度计算。',
    'Uphill Speed Penalty': '上坡减速',
    'SLOPES (% of normal): How hard slopes slow you going up. The game normally starts slowing you at 10 degrees and nearly stops you at 55. 175 reaches the same slowdown at a much shallower angle. 0 removes uphill slowdown. 100 = normal.': '坡度（正常值的百分比）：上坡减速的强度。原版从 10 度开始减速、55 度几乎走不动。设为 175 时很缓的坡就会达到同样减速。0 = 取消上坡减速。100 = 正常。',
    'Downhill Speed Bonus': '下坡加速',
    "SLOPES (EXPERIMENTAL, % bonus): Extra running speed downhill, rising from 5 to 25 degrees of slope. Also replaces the game's slowdown on steep descents. If the game caps speed at normal, this has no effect. 0 = normal game behavior.": '坡度（实验性，加速百分比）：下坡时的额外奔跑速度，从 5 度坡开始提升、到 25 度达到最大。同时取代原版在陡下坡的减速。若游戏本身把速度限制在正常值，则本项无效。0 = 原版行为。',
    'Uphill Stamina Drain': '上坡耐力消耗',
    'SLOPES (% of normal at 20 degrees): Sprint stamina drain while running up a 20-degree slope. 200 = twice as fast. Scales with steepness and is capped at 40 degrees. Flat ground is unchanged. 100 = normal.': '坡度（20 度坡时的正常值百分比）：上 20 度坡的冲刺耐力消耗。200 = 消耗快一倍。随坡度提高，40 度封顶。平地不受影响。100 = 正常。',
    'Downhill Stamina Drain': '下坡耐力消耗',
    'SLOPES (% of normal at 20 degrees): Sprint stamina drain while running down a 20-degree slope. 50 = half the drain. Scales with steepness and is capped at 40 degrees. 100 = normal.': '坡度（20 度坡时的正常值百分比）：下 20 度坡的冲刺耐力消耗。50 = 消耗减半。随坡度提高，40 度封顶。100 = 正常。',
    'Melee': '近战',
    'MELEE: Momentum damage and the stamina cost per swing below. Momentum: your default melee hits harder the faster you were moving just before the swing (standard diver melee only, not melee weapons).': '近战：下方为冲量伤害与每次挥击的耐力消耗。冲量：挥击前移动越快，默认近战伤害越高（仅限潜兵默认近战，不含近战武器）。',
    'Momentum Damage': '冲量伤害',
    'MELEE (% bonus): Extra damage at full sprint speed. 100 = double damage (75 becomes 150). The bonus rises smoothly from jogging to sprinting and lingers briefly so a sprint-into-swing counts. 0 = normal.': '近战（加成百分比）：全速冲刺时的额外伤害。100 = 伤害翻倍（75 变成 150）。加成从小跑平滑增长到冲刺，并会短暂保留，所以「冲刺接挥击」也算数。0 = 正常。',
    'Momentum Stagger and Push': '冲量硬直与推撞',
    'MELEE: ON applies the same momentum bonus to stagger and push force, so a charging hit knocks enemies around harder. Armor penetration never changes.': '近战：开启后冲量加成同样作用于硬直与推力，冲锋一击能把敌人打得更飞。穿甲值不受影响。',
    'Momentum Armor Pen': '冲量穿甲',
    'MELEE: ON gives your default melee +1 armor penetration while you are moving at sprint speed or faster (sprinting, sliding, diving), so a charging hit can crack armor it normally bounces off. Standard diver melee only.': '近战：处于冲刺速度或更快时（冲刺、滑铲、飞扑），默认近战获得 +1 穿甲，冲锋一击能破开原本会被弹开的装甲。仅限潜兵默认近战。',
    'Momentum on Melee Weapons': '近战武器也享冲量',
    'MELEE: ON applies momentum damage, stagger/push and armor pen to melee weapons (machete, axes, hammers and the rest) as well as the default melee. Their damage values are shared by every diver using them.': '近战：开启后，近战武器（砍刀、斧头、锤子等）与默认近战一样享受冲量伤害、硬直/推力与穿甲。这些武器的伤害数值为所有使用者共用。',
    'Melee Stamina Cost': '近战耐力消耗',
    'MELEE (% of a full bar): Stamina each melee swing takes, as a share of a full bar. 10 = ten swings empty a full bar. Starts working once the mod has confirmed your live stamina, which takes a moment of sprinting in each mission. 0 = no cost.': '近战（占满条的百分比）：每次挥击消耗的耐力，按整条耐力的比例计。10 = 挥十下耗尽一整条。需先确认实时耐力才会生效（每局先冲刺一下）。0 = 不消耗。',
    'No Melee When Exhausted': '力竭时禁止近战',
    'MELEE: ON prevents default melee and melee-weapon attacks while the confirmed live stamina bar is empty. Melee becomes available again as soon as stamina begins recovering.': '近战：开启后，确认实时耐力见底时禁止默认近战与近战武器攻击。耐力一开始回充就恢复可用。',
    'Mantling': '翻越攀爬',
    'MANTLING: Stamina for vaulting and climbing ledges, and whether you can do it on an empty bar. The game normally charges nothing for either.': '翻越攀爬：翻越与攀爬崖边消耗的耐力，以及耐力见底时能否继续。原版这两项都不消耗耐力。',
    'Mantle Stamina Cost': '翻越耐力消耗',
    'MANTLING (% of a full bar): Stamina each successful vault or ledge climb takes. The cost is charged only when the game actually enters its climbing movement state, not when you press the button. 10 = a tenth of a bar. Starts once live stamina is confirmed. 0 = free, as in the base game.': '翻越攀爬（占满条的百分比）：每次成功翻越或攀爬崖边消耗的耐力。只有游戏真正进入攀爬移动状态时才扣，不是按下按键就扣。10 = 消耗十分之一条。需先确认实时耐力才会生效。0 = 免费，与原版相同。',
    'No Mantling When Exhausted': '力竭时禁止翻越',
    'MANTLING: ON stops vaults and ledge climbs while your stamina bar is empty; small steps still work. Needs live stamina confirmed (a moment of sprinting each mission).': '翻越攀爬：开启后耐力见底时无法翻越与攀爬崖边；矮台阶仍可通过。需先确认实时耐力（每局先冲刺一下）。',
    'Run and Gun': '边跑边打',
    'RUN AND GUN: Sprint into firing and you keep running: same speed as your sprint, same stamina drain, and on an empty bar the same tired pace. It lasts as long as you keep shooting and moving. The price is heavy aim sway on the move. Firing from a walk or standing works as normal.': '边跑边打：冲刺中开火可以继续奔跑——速度与冲刺一致、耐力消耗也一致，耐力见底时同样保持力竭时的慢速。只要持续开火并移动就一直有效。代价是移动中瞄准晃动很大。走路或站立时开火则一切如常。',
    'Hipfire Linger': '腰射残留',
    'RUN AND GUN (% of normal): How long you stay in the shooting stance after your last shot before the game lets you sprint again. 50 = half as long. 100 = normal.': '边跑边打（正常值的百分比）：最后一枪之后、游戏允许重新冲刺之前的腰射停留时长。50 = 缩短一半。100 = 正常。',
    'Run and Gun Stamina Drain': '边跑边打耐力消耗',
    'RUN AND GUN (% of sprint drain): Stamina used while firing at a run, compared with sprinting. 100 = the same as sprinting (slopes included). Needs live stamina confirmed (a moment of sprinting each mission). 0 = free.': '边跑边打（占冲刺消耗的百分比）：边跑边开火时的耐力消耗，与冲刺相比。100 = 与冲刺相同（含坡度影响）。需先确认实时耐力（每局先冲刺一下）。0 = 不消耗。',
    'Run and Gun Sway': '边跑边打晃动',
    'RUN AND GUN (% extra): Extra aim sway and recoil sway while firing or aiming on the move, full at jogging speed and above. 200 = three times the sway. Stacks with winded sway. 0 = no penalty.': '边跑边打（额外百分比）：移动中开火或瞄准时的额外瞄准晃动与后坐晃动，达到小跑速度及以上时取满值。200 = 晃动变为三倍。与气喘晃动叠加。0 = 无额外惩罚。',
    'Diagnostics Probe': '诊断探针',
    "DIAGNOSTICS: For developing melee stamina cost. ON + APPLY in a mission records 90 seconds of your diver's state (reads only, changes nothing), then writes TacticalCombatProbe.log. Records once per switch-on. Follow the steps in README.txt.": '诊断：用于开发近战耐力消耗功能。在任务中开启并点「应用」，会记录 90 秒的潜兵状态（仅读取、不做任何修改），然后写入 TacticalCombatProbe.log。每次开启只记录一次。请按 README.txt 的步骤操作。',
    'Preset': '预设',
    'Your own applied settings.': '你自己应用的设置。',
    'PRESETS: Select one, then APPLY to replace every setting below. Editing a setting afterwards switches this to Custom. Vanilla: no changes. Light: a gentle nudge. Tactical: the intended experience. Hardcore: hills hurt, winded aim is rough, crouching is how you recover.': '预设：选一个再点「应用」，即可替换下方所有设置；之后手动改任意一项会切回「自定义」。原版 = 不做改动。轻度 = 轻微调整。战术 = 作者推荐的体验。硬核 = 上坡要命、喘气时瞄准难受、靠蹲下来回气。',
    'Run-N-Gun': '边跑边打',
    'Sprint into firing to keep your running speed while shooting. Turning sideways reduces the benefit when Directional Run-N-Gun is enabled.': '冲刺中开火可保持奔跑速度。开启「定向边跑边打」后，侧向移动会降低效果。',
    'Directional Run-N-Gun': '定向边跑边打',
    'Limits the movement-speed benefit to roughly forward movement. Full benefit within 30 degrees, tapering to zero by 55 degrees.': '把移动速度加成限制在接近正前方的方向。30 度内为满效果，到 55 度时衰减为零。',
    'One-Handed Direction Bypass': '单手武器忽略方向限制',
    'One-handed weapons ignore the directional angle restriction. All secondaries and recognized one-handed primaries keep full Run-N-Gun speed in any movement direction.': '单手武器不受方向角度限制。所有副武器以及可识别为单手持的主武器，在任何移动方向上都能保持完整的边跑边打速度。',
    'Percent of the normal post-shot hipfire linger. Lower values let sprinting resume sooner after the last shot. 100 = vanilla.': '正常「开火后腰射停留」时长的百分比。数值越低，最后一枪之后越早能重新冲刺。100 = 原版。',
    'Run-N-Gun Sway': '边跑边打晃动',
    'Extra aim/recoil sway while firing on the move. 200 = roughly triple the affected sway. 0 = no extra sway.': '移动中开火时的额外瞄准/后坐晃动。200 = 受影响的晃动约为三倍。0 = 无额外晃动。',
    "Puts the Bastion and Maelstrom gunner camera lower and further back so you see more around the tank. It stays behind the turret as it turns. The pick is where the camera starts: the mouse wheel (or the Mod Bindings Menu's Zoom In / Zoom Out keys) moves it closer or further back, and from the closest point zooms in on the crosshair.": '把堡垒与漩涡的炮手视角放低、后移，让你能看清坦克周围的更多情况；炮塔转动时视角始终跟在炮塔后方。此项选择的是视角的起始距离：滚轮（或「模组按键菜单」里的放大/缩小键）可以拉近拉远；从最近处再继续就是向准星变焦。',
    "While you drive from the gunner seat with Gunner Drive, a panel like the driver's own HUD shows the gear, rpm, speed, fuel and the Maelstrom's smoke rounds. It only shows while you are the one driving. Only you see it.": '当你用「炮手座驾驶」在炮手位开车时，会显示一块与驾驶员 HUD 类似的面板，内容有挡位、转速、速度、燃料以及漩涡的烟雾弹存量。只有你本人在驾驶时才显示，也只有你自己能看到。',
    'More track grip for the Bastion and Maelstrom: less sliding on slopes and in turns. Tanks called in after a change use it.': '提升堡垒与漩涡的履带抓地力：在斜坡与转弯时更不容易打滑。改动后新召唤的坦克才会生效。',
    'More pulling power for the Bastion and Maelstrom: quicker off the line and up slopes. Top speed is unchanged. Tanks called in after a change use it.': '提升堡垒与漩涡的牵引力：起步与爬坡更快。最高速度不变。改动后新召唤的坦克才会生效。',
    'Quicker steering for the Bastion and Maelstrom: they start and stop turning sooner. Tanks called in after a change use it.': '提升堡垒与漩涡的转向响应：开始与停止转向都更干脆。改动后新召唤的坦克才会生效。',
    "Drive from the gunner seat when the driver seat is empty: your movement keys drive, shift and CTRL change gear, Space is the handbrake. F sounds the horn; Mouse 3 pops the Maelstrom's smoke. Controller: the left stick drives, its click is the horn, the right stick click pops smoke. Set your own keys with the Mod Bindings Menu. A teammate who takes the wheel drives. Pick which vehicles.": '驾驶位空着时可以从炮手位开车：方向键即驾驶，Shift 与 Ctrl 换挡，空格是手刹；F 按喇叭，鼠标中键放漩涡的烟雾。手柄：左摇杆驾驶、按下是喇叭，右摇杆按下放烟雾。可用「模组按键菜单」自定义按键。队友坐上驾驶位时由他开。可勾选适用于哪些载具。',
    'How fast the Bastion and Maelstrom turrets turn (the game: 25 degrees a second), and the gunner view left/right with them. Very fast is 75. With MBT Turrets all the way round a change applies at once; otherwise tanks called in after a change use it. The view: from the next time you sit in the gunner seat.': '堡垒与漩涡炮塔的转速（原版为每秒 25 度），以及炮手视角随之左右转动的速度。最快档为 75。若已启用「360 度主战坦克炮塔」，改动立即生效；否则改动后新召唤的坦克才生效。视角则从你下次坐上炮手位时生效。',
    'How fast the Bastion and Maelstrom guns move up and down (the game: 35 degrees a second), and the gunner view up/down with them. Tanks called in after a change use it.': '堡垒与漩涡火炮的俯仰速度（原版为每秒 35 度），以及炮手视角随之上下转动的速度。改动后新召唤的坦克才会生效。',
    'How far down and up the Bastion and Maelstrom guns aim (the game: 3 below to 25 above). Tanks called in after a change use it.': '堡垒与漩涡火炮的俯仰范围（原版为下 3 度至上 25 度）。改动后新召唤的坦克才会生效。',
    'Native: the game font and smooth icons, in line with ': '原生：使用游戏字体与平滑图标，风格与 ',
    'Nudge the badge sideways, in 1440p pixels (negative = left). ': '把标记左右微调，单位是 1440p 像素（负数 = 向左）。',
    'Nudge the badge up or down, in 1440p pixels (negative = up). ': '把标记上下微调，单位是 1440p 像素（负数 = 向上）。',
    'Another HUD mod may ': '其它 HUD 模组可能',
    'Detailed log (Logs/AggroCounter.log) for bug reports; F8 then marks the moment. ': '在 Logs/AggroCounter.log 输出详细日志以便反馈问题；按 F8 会在日志里标记当前时刻。',
    'Throw C4': '投掷 C4',
    'Detonate C4': '引爆 C4',
    'Require Muscle Enhancement': '需要「肌肉强化」加持',
    'Running with a heavy object only works when someone in the mission brought the Muscle ': '只有任务中有人带了「肌肉强化」，负重奔跑才会生效',
    'Enable every physics system for layout ': '为以下骨架启用全部物理系统：',
    'auto': '自动',
    'Max Dive Water Depth': '最大入水深度',
    "Deepest water, measured up from your feet, that a dive can start in: from 0.20 (lower shin, the original limit) up to 1.30, where your Helldiver starts swimming. Deeper water always keeps the game's normal behavior.": '潜水的最大入水深度，从脚底往上量：0.20（小腿下段，原版上限）到 1.30（此时潜兵会开始游泳）。更深的水域始终沿用游戏原本的行为。',
    'BATTLEFIELD V KILL FEEDBACK / 战地V击杀反馈': '战地V击杀反馈',
    'Battlefield V Kill Feedback / 战地V击杀反馈': '战地V击杀反馈',
    'Battlefield V Kill Feedback/战地V击杀反馈': '战地V击杀反馈',
    'TACTICAL COMBAT OVERHAUL': '战术战斗大修',
    'Tactical Combat Overhaul': '战术战斗大修',
    'SHALLOW WATER DIVING': '浅水潜行',
    'HD2 TRANSMOG': 'HD2 幻化',
    'Running with a heavy object only works when someone in the mission brought the Muscle Enhancement booster. Without it you carry at the normal speed.': '只有任务中有人带了「肌肉强化」增益时，负重奔跑才会生效；否则只能按正常速度搬运。',
    '高度警戒 / High Alert': '高度警戒',
    'High Alert': '高度警戒',
    'Split Colors': '分色显示',
    'Normal Radius': '普通半径',
    'Normal Spread': '普通扩散',
    'Normal Color': '普通颜色',
    'Normal Brightness': '普通亮度',
    'Normal Tone': '普通色调',
    'Normal Opacity': '普通不透明度',
    'Normal Range': '普通探测范围',
    'Normal Boost': '普通增强',
    'Normal Rate': '普通闪烁频率',
    'Heavy Radius': '重型半径',
    'Heavy Spread': '重型扩散',
    'Heavy Color': '重型颜色',
    'Heavy Brightness': '重型亮度',
    'Heavy Tone': '重型色调',
    'Heavy Opacity': '重型不透明度',
    'Heavy Range': '重型探测范围',
    'Heavy Boost': '重型增强',
    'Heavy Rate': '重型闪烁频率',
    'Artillery On': '炮击警报',
    'Artillery Radius': '炮击半径',
    'Artillery Spread': '炮击扩散',
    'Artillery Color': '炮击颜色',
    'Artillery Brightness': '炮击亮度',
    'Artillery Tone': '炮击色调',
    'Artillery Opacity': '炮击不透明度',
    'Artillery Range': '炮击探测范围',
    'Artillery Boost': '炮击增强',
    'Artillery Rate': '炮击闪烁频率',
    'Heavy alerts take priority. Turn off to use Normal settings for all enemies.': '重型警报优先。关闭后所有敌人一律使用「普通」那套设置。',
    'Bloom depth: 1-30% of screen height; default 10.0%. Sets inward glow reach; highlight stays thin.': '光晕深入：屏幕高度的 1-30%，默认 10.0%。决定光晕能向内扩散多远；高亮描边始终保持细线。',
    'On: glow span and depth grow linearly to maximum at 3 m. Off: fixed radius.': '开启：光晕范围与深入随距离线性增长，3 米时达到最大。关闭：半径固定不变。',
    'Default: Yellow. Presets: Yellow, Orange, Red, Blue, White, Pink, Purple.': '默认：黄色。预设：黄、橙、红、蓝、白、粉、紫。',
    'Base brightness: 1-5x; default 3.0x; step 0.1. Original proximity response is preserved.': '基础亮度：1-5 倍，默认 3.0 倍，步进 0.1。保留原版的靠近响应曲线。',
    'Color tone: 0-1; default 0.8. 0 is black; 1 is full color. Original proximity response is preserved.': '颜色色调：0-1，默认 0.8。0 为黑色，1 为纯色。保留原版的靠近响应曲线。',
    'Opacity: 0-1; default 0.6. 0 is invisible; 1 is most visible. Original proximity response is preserved.': '不透明度：0-1，默认 0.6。0 为完全不可见，1 为最明显。保留原版的靠近响应曲线。',
    'Detection range: 5-30 m; default 12.1 m; step 0.1. Only living enemies targeting you trigger alerts.': '探测范围：5-30 米，默认 12.1 米，步进 0.1。只有正在锁定你的活体敌人才会触发警报。',
    'Master proximity boost. Rate and radius grow linearly to maximum at 3 m; brightness and opacity keep their original curves.': '靠近增强总开关。闪烁频率与半径随距离线性增长、3 米时达到最大；亮度与不透明度仍沿用原版曲线。',
    'Max flash rate: 1-5x; default 3.0x. Reaches maximum at 3 m. Set to 1 for base rate.': '最大闪烁频率：1-5 倍，默认 3.0 倍。3 米时达到最大。设为 1 则使用基础频率。',
    'Bloom depth: 1-30% of screen height; default 12.0%. Sets inward glow reach; highlight stays thin.': '光晕深入：屏幕高度的 1-30%，默认 12.0%。决定光晕能向内扩散多远；高亮描边始终保持细线。',
    'On: glow span and depth grow linearly to maximum at 6 m. Off: fixed radius.': '开启：光晕范围与深入随距离线性增长，6 米时达到最大。关闭：半径固定不变。',
    'Default: Red. Presets: Yellow, Orange, Red, Blue, White, Pink, Purple.': '默认：红色。预设：黄、橙、红、蓝、白、粉、紫。',
    'Detection range: 5-30 m; default 20.1 m; step 0.1. Only living enemies targeting you trigger alerts.': '探测范围：5-30 米，默认 20.1 米，步进 0.1。只有正在锁定你的活体敌人才会触发警报。',
    'Master proximity boost. Rate and radius grow linearly to maximum at 6 m; brightness and opacity keep their original curves.': '靠近增强总开关。闪烁频率与半径随距离线性增长、6 米时达到最大；亮度与不透明度仍沿用原版曲线。',
    'Max flash rate: 1-5x; default 2.0x. Reaches maximum at 6 m. Set to 1 for base rate.': '最大闪烁频率：1-5 倍，默认 2.0 倍。6 米时达到最大。设为 1 则使用基础频率。',
    'Cannon alerts; highest priority per direction. Includes cannon towers, small turrets, Factory Strider and Vox main cannons.': '炮击警报；在同一方向上优先级最高。涵盖加农炮塔、小型炮塔、工厂机兽与 Vox 主炮。',
    'Default: bright Red (tone 1.0). Presets: Yellow, Orange, Red, Blue, White, Pink, Purple.': '默认：亮红色（色调 1.0）。预设：黄、橙、红、蓝、白、粉、紫。',
    'Color tone: 0-1; default 1.0. 0 is black; 1 is full color. Original proximity response is preserved.': '颜色色调：0-1，默认 1.0。0 为黑色，1 为纯色。保留原版的靠近响应曲线。',
    'Detection range: 50-200 m; default 200.0 m; step 0.1. Only living cannons targeting you or your occupied mech trigger alerts.': '探测范围：50-200 米，默认 200.0 米，步进 0.1。只有正在锁定你、或锁定你所驾驶机甲的活体炮台才会触发警报。',
    'Tank Turret Position': '坦克炮塔位置',
    'Vehicle Loadout': '载具配置',
    'Close (about 1.5 m back)': '近（后移约 1.5 米）',
    'Far (about 3.5 m back)': '远（后移约 3.5 米）',
    'Farther (about 5 m back)': '更远（后移约 5 米）',
    'Farthest (about 6.5 m back)': '最远（后移约 6.5 米）',
    'Fast (x1.1)': '快（x1.1）',
    'Faster (x1.15)': '更快（x1.15）',
    'Fastest (x1.3)': '最快（x1.3）',
    'Strong (x1.2)': '强（x1.2）',
    'Stronger (x1.35)': '更强（x1.35）',
    'Strongest (x1.5)': '最强（x1.5）',
    'Moderate (x1.2)': '适中（x1.2）',
    'Strong (x1.35)': '强（x1.35）',
    'Maximum (x1.5)': '最高（x1.5）',
    'Quick': '迅速',
    'Quicker': '更迅速',
    'Instant': '瞬时',
    'Steady': '平稳',
    'Original': '原版',
    'Centered': '居中',
    'A faster Bastion and Maelstrom: more engine speed and pulling power, forward and in reverse. Changes the tank you are in at once.': '让堡垒与漩涡更快：提升发动机转速与牵引力，前进与倒退都受益。对你当前所在的坦克立即生效。',
    'More engine torque for the Bastion and Maelstrom: quicker off the line and up slopes. Changes the tank you are in at once.': '提升堡垒与漩涡的发动机扭矩：起步更快、爬坡更轻松。对你当前所在的坦克立即生效。',
    'More track grip for the Bastion and Maelstrom: less sliding on slopes and in turns. Changes the tank you are in at once.': '提升堡垒与漩涡的履带抓地力：在斜坡与转弯时更不容易打滑。对你当前所在的坦克立即生效。',
    'Keeps the Bastion and Maelstrom on the ground: pressed down harder the faster they go, so they stay flat over crests and bumps instead of floating. Changes the tank you are in at once.': '把堡垒与漩涡牢牢压在地面上：速度越快下压力越大，越过坡顶与颠簸时不再飘起来。对你当前所在的坦克立即生效。',
    'Quicker steering for the Bastion and Maelstrom: they start and stop turning sooner. Changes every tank at once.': '让堡垒与漩涡转向更利落：开始与停止转向都更及时。对场上所有坦克立即生效。',
    'Snappier Bastion and Maelstrom: the throttle and brake let go sooner, and gear and direction changes wait less (Instant: no wait). Changes every tank at once.': '让堡垒与漩涡更跟手：松开油门与刹车后动力更快切断，换挡与换向的等待更短（「瞬时」= 完全不等）。对场上所有坦克立即生效。',
    "Drive from the gunner seat when the driver seat is empty: your movement keys drive, shift and CTRL change gear, Space is the handbrake. F sounds the horn; Mouse 3 pops the Maelstrom's smoke. Controller: the left stick drives, its click is the horn, the right stick click pops smoke. Keys set in the Mod Bindings Menu replace these. A teammate who takes the wheel drives. Pick which vehicles.": '驾驶位空着时可以直接从炮手位开车：移动键负责行驶，Shift 与 CTRL 换挡，空格是手刹。F 按喇叭；鼠标中键放出漩涡的烟雾。手柄：左摇杆行驶，按下左摇杆按喇叭，按下右摇杆放烟雾。「模组按键菜单」里设过的键会覆盖以上默认值。队友抢到方向盘时由队友驾驶。可选择对哪些载具生效。',
    "MBT Turrets: where the Bastion and Maelstrom turret sits. Original is the game's place. Centered puts it in the middle of the hull like a main battle tank: the gun reaches past the front deck, so it clips less when aimed low. Changes at once. The tank's hit areas stay the game's own.": '主战坦克炮塔：决定堡垒与漩涡的炮塔坐在哪。选「原版」就是游戏本来的位置；选「居中」会把炮塔移到车体正中间，像真正的主战坦克那样，炮管能越过前甲板，俯角瞄低时穿模更少。立即生效。坦克的受击判定仍沿用游戏原版。',
    'How fast the Bastion and Maelstrom turrets turn (the game: 25 degrees a second), and the gunner view left/right with them. Very fast is 75. Changes every tank at once; the view from the next time you sit in the gunner seat.': '堡垒与漩涡炮塔的转动速度（游戏原版：每秒 25 度），炮手视角的左右转动会同步跟随。「极快」为 75。对场上所有坦克立即生效；视角要等下次坐进炮手位时才刷新。',
    'How fast the Bastion and Maelstrom guns move up and down (the game: 35 degrees a second), and the gunner view up/down with them. Changes every tank at once; the view from the next time you sit in the gunner seat.': '堡垒与漩涡火炮的俯仰速度（游戏原版：每秒 35 度），炮手视角的上下转动会同步跟随。对场上所有坦克立即生效；视角要等下次坐进炮手位时才刷新。',
    'How far down and up the Bastion and Maelstrom guns aim (the game: 3 below to 25 above), and the gunner view up/down with them. Changes every tank at once; the view from the next time you sit in the gunner seat.': '堡垒与漩涡火炮的俯仰范围（游戏原版：向下 3 度、向上 25 度），炮手视角的上下活动范围会同步跟随。对场上所有坦克立即生效；视角要等下次坐进炮手位时才刷新。',
    "Pick more than one tank, exosuit or FRV in your stratagem loadout (the game puts a second one in the first one's slot). Changes at once; turning it off puts the game's limit back.": '允许在战备配置里同时带多辆坦克、机甲或快速侦察车（游戏原本会把第二辆塞进第一辆的格子里）。立即生效；关闭后恢复游戏的原有上限。',
    "Requires this layout's Custom rig. Off: no IK. On: full IK. Auto: full IK with weapon contact. Partial: layout XYZ weights. Auto (Partial): full IK with contact, partial otherwise. Original hand orientation is retained.": '需要该布局带 Custom（自订）骨骼。关闭：不做 IK。开启：完整 IK。自动：完整 IK，并处理武器接触。部分：按布局的 XYZ 权重。自动（部分）：有接触时用完整 IK，其余情况用部分 IK。手部原始朝向保持不变。',
    'Partial': '部分',
    'Auto (Partial)': '自动（部分）',
    'Row text': '行文本',
    'Shown beside the rows -- while the option is selected': '在行旁显示 —— 仅当该选项被选中时',
    'Yellow': '黄色',
    'Orange': '橙色',
    'Blue': '蓝色',
    'White': '白色',
    'Pink': '粉色',
    'Purple': '紫色',
}
